#include "StoryData.h"

void StoryData::Initialize()
{
    // 인트로 대사.txt의 초반 인트로와 히로인 첫 만남 대사를 순서대로 넣는다.
    introStory =
    {
        { L"", L"봄이었다.", L"school_day", L"", L"", L"story1" },
        { L"", L"교실 창문 너머로 벚꽃잎이 느리게 떨어지고 있었다.", L"school_day", L"" },
        { L"담임", L"이번 주 금요일까지 진로 희망 조사서 제출하고, 동아리 활동 보고서도 잊지 말고.", L"school_day", L"" },
        { L"{PLAYER}", L"하암……", L"school_day", L"" },
        { L"", L"평범했다. 너무 평범해서 지루할 정도로.", L"school_day", L"" },
        { L"", L"{PLAYER}는 반에서 크게 눈에 띄는 학생은 아니었다.", L"school_day", L"" },
        { L"", L"적당히 인사하고, 적당히 웃고, 수업이 끝나면 조용히 집에 가는 것.", L"school_day", L"" },
        { L"", L"그게 {PLAYER}가 바라는 학교생활의 전부였다.", L"school_day", L"" },
        { L"담임", L"자, 오늘 수업은 여기까지. 다들 조심히 들어가라.", L"school_day", L"" },
        { L"", L"하지만 그날 방과 후, {PLAYER}의 평범한 봄은 끝났다.", L"school_day", L"" },
        { L"", L"수업이 끝난 뒤, {PLAYER}는 가방을 챙겨 복도를 걸었다.", L"school_hallway", L"" },
        { L"", L"복도 끝에는 낡은 동아리방 하나가 있었다.", L"school_hallway", L"" },
        { L"{PLAYER}", L"문예부실……? 이런 곳도 있었나.", L"school_hallway", L"" },
        { L"", L"문에는 붉은 도장이 찍힌 안내문이 붙어 있었다.", L"school_hallway", L"" },
        { L"", L"폐부 예정. 정리 담당, 학생회.", L"school_hallway", L"" },
        { L"{PLAYER}", L"그냥 지나가자.", L"school_hallway", L"" },
        { L"{PLAYER}", L"응?", L"school_hallway", L"" },
        { L"", L"{PLAYER}의 발끝에 검은색 노트 하나가 걸렸다.", L"school_hallway", L"" },
        { L"{PLAYER}", L"누가 떨어뜨린 건가?", L"school_hallway", L"" },
        { L"", L"{PLAYER}는 노트를 주워 첫 장을 펼쳤다.", L"school_hallway", L"" },
        { L"노트", L"혼자 남는 순간, 봄은 다시 시작된다.", L"school_hallway", L"" },
        { L"{PLAYER}", L"……뭐야, 이거.", L"school_hallway", L"" },
        { L"{PLAYER}", L"문예부에서 쓰던 설정 노트 같은 건가?", L"school_hallway", L"" },
        { L"", L"{PLAYER}는 찝찝한 기분을 느끼면서도 노트를 가방 안에 넣었다.", L"school_hallway", L"" },
        { L"", L"그날 저녁, {PLAYER}는 혼자 집으로 돌아가고 있었다.", L"school_hallway", L"" },
        { L"{PLAYER}", L"오늘도 별일 없이 끝났네.", L"school_hallway", L"" },
        { L"", L"그렇게 말한 순간, 주변 소리가 멀어졌다.", L"school_hallway", L"", L"", L"stop" },
        { L"{PLAYER}", L"……어?", L"school_hallway", L"", L"", L"story2"},
        { L"", L"자동차 소리도, 바람 소리도, 자신의 발소리도 멈춘 것 같았다.", L"school_hallway", L"" },
        { L"", L"가방 안의 검은 노트가 희미하게 떨렸다.", L"school_hallway", L"" },
        { L"{PLAYER}", L"뭐야…… 왜 이래?", L"school_hallway", L"" },
        { L"", L"시야가 새하얗게 번졌다.", L"school_hallway", L"" },
        { L"담임", L"이번 주 금요일까지 진로 희망 조사서 제출하고, 동아리 활동 보고서도 잊지 말고.", L"school_day", L"" },
        { L"{PLAYER}", L"……?", L"school_day", L"" },
        { L"", L"{PLAYER}는 천천히 고개를 들었다.", L"school_day", L"" },
        { L"", L"교실. 칠판. 담임 선생님. 창밖의 봄.", L"school_day", L"" },
        { L"{PLAYER}", L"잠깐만…… 방금 나 집에 가고 있었는데?", L"school_day", L"" },
        { L"", L"{PLAYER}는 급하게 가방을 열었다.", L"school_day", L"" },
        { L"", L"검은 노트가 들어 있었다.", L"school_day", L"" },
        { L"{PLAYER}", L"말도 안 돼.", L"school_day", L"" },
        { L"노트", L"첫 번째 반복.", L"school_day", L"" },
        { L"{PLAYER}", L"……반복?", L"school_day", L"" },
        { L"", L"처음에는 꿈이라고 생각했다.", L"school_day", L"" },
        { L"", L"하지만 하루는 지나치게 똑같았다.", L"school_day", L"" },
        { L"", L"복도에서 우유를 쏟는 학생. 운동장에서 날아와 창문을 두드리는 축구공. 방송실의 이상한 잡음.", L"school_hallway", L"" },
        { L"{PLAYER}", L"다 똑같잖아……", L"school_day", L"" },
        { L"{PLAYER}", L"야, 잠깐만.", L"school_day", L"" },
        { L"친구", L"왜?", L"school_day", L"" },
        { L"{PLAYER}", L"이상하게 들릴 수도 있는데……", L"school_day", L"" },
        { L"{PLAYER}", L"오늘이 반복되고 있어.", L"school_day", L"" },
        { L"", L"교실의 모든 소리가 끊겼다.", L"school_day", L"" },
        { L"친구", L"……", L"school_day", L"" },
        { L"", L"창밖에서 떨어지던 벚꽃잎이 공중에 멈췄다.", L"school_day", L"" },
        { L"{PLAYER}", L"아.", L"school_day", L"" },
        { L"담임", L"이번 주 금요일까지 진로 희망 조사서 제출하고—", L"school_day", L"" },
        { L"{PLAYER}", L"또야……", L"school_day", L"" },
        { L"", L"{PLAYER}는 책상 위에 엎드린 채 눈을 떴다.", L"school_day", L"" },
        { L"", L"심장이 미친 듯이 뛰고 있었다.", L"school_day", L"" },
        { L"노트", L"반복을 말하지 마라.\n말하는 순간, 봄은 닫힌다.", L"school_day", L"" },
        { L"{PLAYER}", L"말하지도 못하고, 혼자 있어도 안 되고……", L"school_day", L"" },
        { L"{PLAYER}", L"그럼 나보고 뭘 하라는 건데.", L"school_day", L"" },
        { L"노트", L"혼자 남는 순간, 봄은 다시 시작된다.", L"school_day", L"" },
        { L"{PLAYER}", L"혼자 있지 말라는 건가?", L"school_day", L"", L"", L"stop"},
        { L"", L"그때, 옆에서 익숙한 목소리가 들렸다.", L"school_day", L"", L"", L"story3"},
        { L"유하린", L"{PLAYER}.", L"school_day", L"yuharin_normal" },
        { L"{PLAYER}", L"깜짝이야.", L"school_day", L"yuharin_normal" },
        { L"유하린", L"너 오늘 표정 진짜 레전드다.", L"school_day", L"yuharin_smile" },
        { L"{PLAYER}", L"뭐가.", L"school_day", L"yuharin_normal" },
        { L"유하린", L"세상 멸망하는 꿈이라도 꿨어?", L"school_day", L"yuharin_normal" },
        { L"{PLAYER}", L"그냥…… 잠을 좀 못 잤어.", L"school_day", L"yuharin_normal" },
        { L"유하린", L"잠 못 잔 얼굴이 아니라, 인생 세이브 파일 날아간 얼굴인데?", L"school_day", L"yuharin_normal" },
        { L"{PLAYER}", L"……뭐?", L"school_day", L"yuharin_normal" },
        { L"유하린", L"왜 그렇게 놀라? 그냥 비유잖아.", L"school_day", L"yuharin_normal" },
        { L"", L"하린은 장난스럽게 웃었다.", L"school_day", L"yuharin_smile" },
        { L"유하린", L"아무튼 너 오늘 혼자 두면 안 될 것 같아.", L"school_day", L"yuharin_normal" },
        { L"{PLAYER}", L"왜?", L"school_day", L"yuharin_normal" },
        { L"유하린", L"재미없어 보여서.", L"school_day", L"yuharin_smile" },
        { L"{PLAYER}", L"그게 이유야?", L"school_day", L"yuharin_normal" },
        { L"유하린", L"응. 엄청 중요한 이유지.", L"school_day", L"yuharin_normal" },
        { L"유하린", L"방과 후에 매점 가자.", L"school_day", L"yuharin_normal" },
        { L"{PLAYER}", L"내가 왜?", L"school_day", L"yuharin_normal" },
        { L"유하린", L"내가 가자고 했으니까.", L"school_day", L"yuharin_normal" },
        { L"{PLAYER}", L"그게 이유가 돼?", L"school_day", L"yuharin_normal" },
        { L"유하린", L"나한테는 돼.", L"school_day", L"yuharin_smile" },
        { L"", L"평소 같았으면 대충 거절했을 것이다.", L"school_day", L"yuharin_normal" },
        { L"", L"하지만 노트의 문장이 계속 머릿속에 맴돌았다.", L"school_day", L"yuharin_normal" },
        { L"{PLAYER}", L"……알았어. 잠깐만.", L"school_day", L"yuharin_normal" },
        { L"유하린", L"좋아. 오늘의 {PLAYER} 구출 작전 시작.", L"school_day", L"yuharin_smile" },
        { L"{PLAYER}", L"그런 작전 필요 없는데.", L"school_day", L"yuharin_normal" },
        { L"유하린", L"필요 있어. 네 얼굴이 이미 구조 요청 중이야.", L"school_day", L"yuharin_normal" },
        { L"", L"하린과 함께한 방과 후는 이상할 정도로 평범했다.", L"school_day", L"yuharin_normal" },
        { L"", L"매점에서 빵을 사고, 복도에서 친구들과 마주치고, 운동장 옆 벤치에 앉아 음료수를 마셨다.", L"school_hallway", L"yuharin_normal" },
        { L"유하린", L"{PLAYER} 너는 왜 이렇게 조용하냐?", L"school_day", L"yuharin_normal" },
        { L"{PLAYER}", L"그냥.", L"school_day", L"yuharin_normal" },
        { L"유하린", L"그냥이 제일 재미없는 대답인 거 알아?", L"school_day", L"yuharin_smile" },
        { L"{PLAYER}", L"그럼 뭐라고 해야 하는데?", L"school_day", L"yuharin_normal" },
        { L"유하린", L"나는 사실 엄청난 비밀을 숨기고 있다든가.", L"school_day", L"yuharin_normal" },
        { L"{PLAYER}", L"……", L"school_day", L"yuharin_normal" },
        { L"유하린", L"뭐야, 진짜 있어?", L"school_day", L"yuharin_normal" },
        { L"{PLAYER}", L"없어.", L"school_day", L"yuharin_normal" },
        { L"유하린", L"두 번 말하면 더 수상한 거 몰라?", L"school_day", L"yuharin_normal" },
        { L"", L"하린은 웃었지만, 이상하게 더 캐묻지는 않았다.", L"school_day", L"yuharin_smile" },
        { L"", L"시간은 천천히 흘렀다.", L"school_day", L"yuharin_normal" },
        { L"{PLAYER}", L"오후 6시……", L"school_day", L"yuharin_normal" },
        { L"유하린", L"왜? 시간 약속 있어?", L"school_day", L"yuharin_normal" },
        { L"{PLAYER}", L"아니. 그냥.", L"school_day", L"yuharin_normal" },
        { L"", L"지금까지라면 이미 세상이 일그러졌어야 할 시간이었다.", L"school_day", L"yuharin_normal" },
        { L"", L"하지만 아무 일도 일어나지 않았다.", L"school_day", L"yuharin_normal" },
        { L"유하린", L"오늘 하늘 예쁘다.", L"school_day", L"yuharin_smile" },
        { L"{PLAYER}", L"……그러게.", L"school_day", L"yuharin_normal" },
        { L"", L"{PLAYER}는 처음으로 생각했다.", L"school_day", L"yuharin_normal" },
        { L"", L"오늘이, 앞으로 가고 있다고.", L"school_day", L"yuharin_normal" },
        { L"", L"그날 밤, {PLAYER}는 쉽게 잠들지 못했다.", L"room", L"" },
        { L"{PLAYER}", L"또 같은 교실에서 눈뜨는 건 아니겠지……", L"room", L"" },
        { L"", L"책상 위의 검은 노트가 저절로 펼쳐졌다.", L"room", L"" },
        { L"노트", L"함께 있으면, 봄은 앞으로 흐른다.", L"room", L"" },
        { L"{PLAYER}", L"함께 있으면……", L"room", L"" },
        { L"", L"{PLAYER}는 그 문장을 한참 바라보다가 천천히 눈을 감았다.", L"room", L"" },
        { L"{PLAYER}", L"……?", L"room", L"" },
        { L"", L"{PLAYER}는 눈을 번쩍 떴다.", L"room", L"" },
        { L"", L"교실이 아니었다. 담임의 목소리도 들리지 않았다.", L"room", L"" },
        { L"{PLAYER}", L"내 방……?", L"room", L"" },
        { L"", L"휴대폰 화면에는 어제와 다른 날짜가 떠 있었다.", L"room", L"" },
        { L"{PLAYER}", L"넘어갔어……", L"room", L"" },
        { L"", L"{PLAYER}는 급하게 검은 노트를 펼쳤다.", L"room", L"" },
        { L"노트", L"첫 번째 연결이 시작되었다.\n유하린.\n웃음 뒤에 숨긴 봄의 작별.", L"room", L"" },
        { L"{PLAYER}", L"유하린……", L"room", L"" },
        { L"노트", L"이 봄은 혼자서는 지나갈 수 없다.\n누군가와 시간을 보내고, 마음에 닿아라.", L"room", L"" },
        { L"노트", L"선택은 관계를 만들고, 관계는 시간을 움직인다.", L"room", L"" },
        { L"{PLAYER}", L"말할 수는 없지만…… 다가갈 수는 있다.", L"room", L"" },
        { L"", L"{PLAYER}는 노트를 조용히 덮었다.", L"room", L"" },
        { L"", L"반복되던 봄은 아직 끝나지 않았다.", L"school_day", L"" },
        { L"", L"하지만 처음으로, {PLAYER}는 이 봄이 아주 조금 앞으로 움직였다는 것을 알았다.", L"school_day", L"" },
        { L"시스템", L"앞으로 하루가 시작될 때마다 {PLAYER}는 행동을 선택할 수 있습니다." },
        { L"시스템", L"선택한 인물과 시간을 보내면 해당 인물의 선택 횟수가 증가합니다." },
        { L"시스템", L"미니게임 결과에 따라 {PLAYER}의 스탯이 상승합니다." },
        { L"시스템", L"마지막에는 가장 많이 선택한 히로인이 최종 선택지에 등장합니다." },
        { L"시스템", L"해피엔딩을 위해서는 선택 기록과 스탯이 모두 중요합니다." },
        { L"유하린", L"{PLAYER}.", L"school_day", L"yuharin_normal" },
        { L"{PLAYER}", L"깜짝이야.", L"school_day", L"yuharin_normal" },
        { L"유하린", L"너 오늘 표정 진짜 레전드다.", L"school_day", L"yuharin_smile" },
        { L"{PLAYER}", L"뭐가.", L"school_day", L"yuharin_normal" },
        { L"유하린", L"세상 멸망하는 꿈이라도 꿨어?", L"school_day", L"yuharin_normal" },
        { L"{PLAYER}", L"그냥…… 잠을 좀 못 잤어.", L"school_day", L"yuharin_normal" },
        { L"유하린", L"잠 못 잔 얼굴이 아니라, 인생 세이브 파일 날아간 얼굴인데?", L"school_day", L"yuharin_normal" },
        { L"{PLAYER}", L"……뭐?", L"school_day", L"yuharin_normal" },
        { L"유하린", L"왜 그렇게 놀라? 그냥 비유잖아.", L"school_day", L"yuharin_normal" },
        { L"", L"하린은 장난스럽게 웃었다.", L"school_day", L"yuharin_smile" },
        { L"유하린", L"아무튼 너 오늘 혼자 두면 안 될 것 같아.", L"school_day", L"yuharin_normal" },
        { L"{PLAYER}", L"왜?", L"school_day", L"yuharin_normal" },
        { L"유하린", L"재미없어 보여서.", L"school_day", L"yuharin_smile" },
        { L"{PLAYER}", L"그게 이유야?", L"school_day", L"yuharin_normal" },
        { L"유하린", L"응. 엄청 중요한 이유지.", L"school_day", L"yuharin_normal" },
        { L"유하린", L"방과 후에 매점 가자.", L"school_day", L"yuharin_normal" },
        { L"{PLAYER}", L"내가 왜?", L"school_day", L"yuharin_normal" },
        { L"유하린", L"내가 가자고 했으니까.", L"school_day", L"yuharin_normal" },
        { L"{PLAYER}", L"그게 이유가 돼?", L"school_day", L"yuharin_normal" },
        { L"유하린", L"나한테는 돼.", L"school_day", L"yuharin_smile" },
        { L"", L"평소 같았으면 대충 거절했을 것이다.", L"school_day", L"yuharin_normal" },
        { L"", L"하지만 노트의 문장이 계속 머릿속에 맴돌았다.", L"school_day", L"yuharin_normal" },
        { L"{PLAYER}", L"……알았어. 잠깐만.", L"school_day", L"yuharin_normal" },
        { L"유하린", L"좋아. 오늘의 {PLAYER} 구출 작전 시작.", L"school_day", L"yuharin_smile" },
        { L"{PLAYER}", L"그런 작전 필요 없는데.", L"school_day", L"yuharin_normal" },
        { L"유하린", L"필요 있어. 네 얼굴이 이미 구조 요청 중이야.", L"school_day", L"yuharin_normal", L"", L"stop"},
        { L"", L"다음 날 방과 후, {PLAYER}는 검은 노트가 처음 발견된 문예부실 앞으로 향했다.", L"school_hallway", L"hansea_normal", L"", L"story4"},
        { L"{PLAYER}", L"역시 여기서부터 다시 확인해보는 게 맞겠지.", L"school_hallway", L"hansea_normal" },
        { L"", L"문예부실 문 앞에는 여전히 폐부 예정 안내문이 붙어 있었다.", L"school_hallway", L"hansea_normal" },
        { L"", L"그때, 복도 안쪽에서 종이 더미가 흔들리는 소리가 들렸다.", L"school_hallway", L"hansea_normal" },
        { L"한세아", L"앗.", L"school_hallway", L"hansea_normal" },
        { L"", L"서류 몇 장이 바닥으로 흩어졌다.", L"school_hallway", L"hansea_normal" },
        { L"{PLAYER}", L"괜찮아?", L"school_hallway", L"hansea_normal" },
        { L"", L"{PLAYER}는 반사적으로 몸을 숙여 서류를 주웠다.", L"school_hallway", L"hansea_normal" },
        { L"한세아", L"고마워. 문예부 폐부 자료가 생각보다 많아서.", L"school_hallway", L"hansea_smile" },
        { L"{PLAYER}", L"학생회가 이런 것도 해?", L"school_hallway", L"hansea_normal" },
        { L"한세아", L"해야 하니까.", L"school_hallway", L"hansea_normal" },
        { L"", L"짧은 대답이었다.", L"school_hallway", L"hansea_normal" },
        { L"", L"그때, {PLAYER}의 가방에서 검은 노트 모서리가 살짝 보였다.", L"school_hallway", L"hansea_normal" },
        { L"한세아", L"잠깐만.", L"school_hallway", L"hansea_normal" },
        { L"{PLAYER}", L"응?", L"school_hallway", L"hansea_normal" },
        { L"한세아", L"그 노트, 문예부 물품이야?", L"school_hallway", L"hansea_normal" },
        { L"{PLAYER}", L"아니, 그건……", L"school_hallway", L"hansea_normal" },
        { L"", L"{PLAYER}는 순간 말을 멈췄다.", L"school_hallway", L"hansea_normal" },
        { L"노트", L"반복을 말하지 마라. 말하는 순간, 봄은 닫힌다.", L"school_hallway", L"hansea_normal" },
        { L"{PLAYER}", L"그냥…… 여기 근처에서 주웠어.", L"school_hallway", L"hansea_normal" },
        { L"한세아", L"그럼 폐부 물품일 수도 있겠네. 확인이 필요해.", L"school_hallway", L"hansea_normal" },
        { L"{PLAYER}", L"꼭 지금 해야 해?", L"school_hallway", L"hansea_normal" },
        { L"한세아", L"응. 오늘 안에 정리해야 하니까.", L"school_hallway", L"hansea_normal" },
        { L"{PLAYER}", L"오늘 안에……", L"school_hallway", L"hansea_normal" },
        { L"", L"{PLAYER}에게 오늘은 아직도 조금 무서운 단어였다.", L"school_hallway", L"hansea_normal" },
        { L"한세아", L"싫으면 안 해도 돼. 하지만 도와주면 고맙겠어.", L"school_hallway", L"hansea_smile" },
        { L"{PLAYER}", L"뭘 하면 되는데?", L"school_hallway", L"hansea_normal" },
        { L"한세아", L"활동 보고서, 예산 자료, 분실물 목록. 세 가지로 나눠주면 돼.", L"school_hallway", L"hansea_normal" },
        { L"{PLAYER}", L"생각보다 본격적이네.", L"school_hallway", L"hansea_normal" },
        { L"한세아", L"폐부 정리는 장난이 아니니까.", L"school_hallway", L"hansea_normal" },
        { L"", L"{PLAYER}는 세아의 옆에 앉아 서류를 정리하기 시작했다.", L"school_hallway", L"hansea_normal" },
        { L"", L"말투는 딱딱했지만, 이상하게 차갑지는 않았다.", L"school_hallway", L"hansea_normal" },
        { L"노트", L"두 번째 연결이 시작되었다.\n한세아.\n완벽해 보이는 봄의 균열.", L"school_hallway", L"hansea_normal" },
        { L"", L"며칠 뒤, 검은 노트에는 새로운 문장이 떠올랐다.", L"library_day", L"seoirin_normal", L"", L"story5"},
        { L"노트", L"오래된 기록은 도서관에 남아 있다.", L"library_day", L"seoirin_normal" },
        { L"{PLAYER}", L"도서관……", L"library_day", L"seoirin_normal" },
        { L"", L"{PLAYER}는 점심시간이 끝난 뒤 도서관으로 향했다.", L"library_day", L"seoirin_normal" },
        { L"", L"도서관 안은 이상할 정도로 조용했다.", L"library_day", L"seoirin_normal" },
        { L"", L"{PLAYER}는 검색대에서 문예부 관련 자료를 찾았다.", L"library_day", L"seoirin_normal" },
        { L"{PLAYER}", L"『봄이 끝나지 않는 날』……?", L"library_day", L"seoirin_normal" },
        { L"", L"낡은 문집 하나가 목록에 남아 있었다.", L"library_day", L"seoirin_normal" },
        { L"", L"{PLAYER}는 구석 서가로 향했다.", L"library_day", L"seoirin_normal" },
        { L"", L"하지만 그 책은 이미 누군가의 손에 들려 있었다.", L"library_day", L"seoirin_normal" },
        { L"서이린", L"……", L"library_day", L"seoirin_normal" },
        { L"{PLAYER}", L"저기.", L"library_day", L"seoirin_normal" },
        { L"서이린", L"늦었네요.", L"library_day", L"seoirin_normal" },
        { L"{PLAYER}", L"네?", L"library_day", L"seoirin_normal" },
        { L"서이린", L"아니에요. 혼잣말이에요.", L"library_day", L"seoirin_normal" },
        { L"", L"소녀는 조용히 책을 덮었다.", L"library_day", L"seoirin_normal" },
        { L"{PLAYER}", L"그 책, 제가 찾던 건데요.", L"library_day", L"seoirin_normal" },
        { L"서이린", L"알아요.", L"library_day", L"seoirin_normal" },
        { L"{PLAYER}", L"알아요?", L"library_day", L"seoirin_normal" },
        { L"서이린", L"이 책을 찾는 사람은 많지 않으니까요.", L"library_day", L"seoirin_normal" },
        { L"{PLAYER}", L"너도 문예부랑 관련 있어?", L"library_day", L"seoirin_normal" },
        { L"서이린", L"아니요.", L"library_day", L"seoirin_normal" },
        { L"{PLAYER}", L"그럼 왜 그 책을 보고 있었어?", L"library_day", L"seoirin_normal" },
        { L"서이린", L"기억하려고요.", L"library_day", L"seoirin_normal" },
        { L"{PLAYER}", L"뭘?", L"library_day", L"seoirin_normal" },
        { L"", L"이린은 대답하지 않았다.", L"library_day", L"seoirin_normal" },
        { L"", L"대신 책 사이에 끼워진 낡은 책갈피를 꺼내 {PLAYER}에게 건넸다.", L"library_day", L"seoirin_normal" },
        { L"서이린", L"오늘은 이것만 가져가요.", L"library_day", L"seoirin_normal" },
        { L"{PLAYER}", L"오늘은?", L"library_day", L"seoirin_normal" },
        { L"서이린", L"네. 아직 봄은 많이 남았으니까.", L"library_day", L"seoirin_normal" },
        { L"{PLAYER}", L"너…… 뭔가 알고 있어?", L"library_day", L"seoirin_normal" },
        { L"서이린", L"알아도 말하면 안 되는 게 있어요.", L"library_day", L"seoirin_normal" },
        { L"", L"{PLAYER}는 그 말에 아무 대답도 하지 못했다.", L"library_day", L"seoirin_normal" },
        { L"", L"이린은 책을 다시 서가에 꽂고 조용히 걸어갔다.", L"library_day", L"seoirin_normal" },
        { L"{PLAYER}", L"잠깐만. 이름은?", L"library_day", L"seoirin_normal" },
        { L"서이린", L"서이린.", L"library_day", L"seoirin_normal" },
        { L"", L"그 이름을 듣는 순간, 가방 안의 검은 노트가 희미하게 떨렸다.", L"library_day", L"seoirin_normal" },
        { L"노트", L"세 번째 연결이 시작되었다.\n서이린.\n기억하고 있는 봄의 책갈피.", L"library_day", L"seoirin_normal" },
        { L"", L"{PLAYER}는 손에 남은 책갈피를 내려다보았다.", L"library_day", L"seoirin_normal" },
        { L"", L"그리고 처음으로 생각했다.", L"library_day", L"seoirin_normal" },
        { L"", L"이린은 이 반복의 진실을 알고 있을지도 모른다고.", L"library_day", L"seoirin_normal" }
    };

    // 선택 이벤트 스토리: 공통 도입 + 선택 히로인 대사 + 공통 마무리.
    storyScripts[0][0] =
    {
        { L"", L"다음 날, 교실은 평소보다 조금 소란스러웠다.", L"school_day", L"", L"", L"story2.1"},
        { L"담임", L"오늘은 둘씩 짝을 지어서 활동지를 작성할 거다.",L"school_day" },
        { L"{PLAYER}", L"짝 활동……",L"school_day" },
        { L"", L"{PLAYER}는 조용히 빈자리를 찾았다.",L"school_day" },
        { L"", L"그 순간, 검은 노트가 가방 안에서 희미하게 떨렸다.",L"school_day" },
        { L"노트", L"선택은 관계를 만들고, 관계는 시간을 움직인다.",L"school_day" },
        { L"{PLAYER}", L"이번에도…… 누군가와 가까워져야 하는 건가.",L"school_day" },
        { L"", L"{PLAYER}의 시선 끝에 세 사람이 보였다.",L"school_day" },
        { L"", L"창가 쪽에서 손을 흔드는 유하린.",L"school_day" },
        { L"", L"앞자리에서 자료를 정리하고 있는 한세아.",L"school_day" },
        { L"", L"교실 뒤쪽에서 조용히 책을 덮는 서이린.",L"school_day" },
        { L"시스템", L"누구 옆에 앉을까?",L"school_day" },
        { L"한세아", L"{PLAYER}?", L"hansea_room", L"hansea_normal" },
        { L"{PLAYER}", L"여기 앉아도 돼?", L"hansea_room", L"hansea_normal" },
        { L"한세아", L"응. 마침 빈자리였어.", L"hansea_room", L"hansea_normal" },
        { L"", L"세아의 책상 위에는 이미 활동지와 필기구가 가지런히 놓여 있었다.", L"room", L"hansea_normal" },
        { L"{PLAYER}", L"준비 빠르네.", L"hansea_room", L"hansea_normal" },
        { L"한세아", L"수업 전에 필요한 건 미리 확인해두는 편이야.", L"hansea_room", L"hansea_normal" },
        { L"{PLAYER}", L"학생회장답다.", L"hansea_room", L"hansea_normal" },
        { L"한세아", L"그런 말은 조금 부담스러워.", L"hansea_room", L"hansea_normal" },
        { L"{PLAYER}", L"아, 미안.", L"hansea_room", L"hansea_normal" },
        { L"한세아", L"아니. 나쁘다는 뜻은 아니야.", L"hansea_room", L"hansea_normal" },
        { L"", L"세아는 잠시 말을 고르더니 활동지를 {PLAYER} 쪽으로 돌렸다.", L"hansea_room", L"hansea_normal" },
        { L"한세아", L"이번 활동은 의견 정리가 중요해. 네 생각도 말해줘.", L"hansea_room", L"hansea_normal" },
        { L"{PLAYER}", L"내 생각?", L"hansea_room", L"hansea_normal" },
        { L"한세아", L"응. 혼자 정리하면 놓치는 게 생기니까.", L"hansea_room", L"hansea_normal" },
        { L"", L"완벽해 보이는 세아가 누군가의 의견을 기다리고 있었다.", L"hansea_room", L"hansea_normal" },
        { L"{PLAYER}", L"그럼…… 같이 해보자.", L"hansea_room", L"hansea_normal" },
        { L"한세아", L"응. 부탁할게.", L"hansea_room", L"hansea_smile" },
        { L"", L"세아의 목소리는 차분했지만, 조금은 안도한 것처럼 들렸다.", L"hansea_room", L"hansea_smile" },
        { L"노트", L"한세아와의 시간이 조금 가까워졌다.", L"hansea_room", L"hansea_normal" },
        { L"시스템", L"한세아 선택 횟수가 증가했습니다.", L"hansea_room", L"hansea_normal" },
        { L"", L"수업이 끝나고, {PLAYER}는 가방 속 검은 노트를 펼쳤다." },
        { L"노트", L"첫 번째 선택이 기록되었다." },
        { L"노트", L"작은 선택은 작은 변화를 만들고, 작은 변화는 봄의 방향을 바꾼다." },
        { L"{PLAYER}", L"이런 식으로…… 앞으로 나아가라는 건가." },
        { L"", L"{PLAYER}는 노트를 덮었다." },
        { L"", L"아직 모든 것을 이해한 것은 아니었다." },
        { L"", L"하지만 한 가지는 분명했다." },
        { L"", L"이제 {PLAYER}의 하루는, 선택에 따라 조금씩 달라지고 있었다.", L"", L"", L"", L"stop"}
    };

    storyScripts[0][1] =
    {
        { L"", L"다음 날, 교실은 평소보다 조금 소란스러웠다.", L"school_day", L"", L"", L"story2.1"},
        { L"담임", L"오늘은 둘씩 짝을 지어서 활동지를 작성할 거다.",L"school_day" },
        { L"{PLAYER}", L"짝 활동……",L"school_day" },
        { L"", L"{PLAYER}는 조용히 빈자리를 찾았다.",L"school_day" },
        { L"", L"그 순간, 검은 노트가 가방 안에서 희미하게 떨렸다.",L"school_day" },
        { L"노트", L"선택은 관계를 만들고, 관계는 시간을 움직인다.",L"school_day" },
        { L"{PLAYER}", L"이번에도…… 누군가와 가까워져야 하는 건가.",L"school_day" },
        { L"", L"{PLAYER}의 시선 끝에 세 사람이 보였다.",L"school_day" },
        { L"", L"창가 쪽에서 손을 흔드는 유하린.",L"school_day" },
        { L"", L"앞자리에서 자료를 정리하고 있는 한세아.",L"school_day" },
        { L"", L"교실 뒤쪽에서 조용히 책을 덮는 서이린.",L"school_day" },
        { L"시스템", L"누구 옆에 앉을까?",L"school_day" },
        { L"유하린", L"오, {PLAYER}. 설마 나랑 짝 하러 온 거야?", L"school_day", L"yuharin_normal" },
        { L"{PLAYER}", L"빈자리가 여기밖에 없어서.", L"school_day", L"yuharin_normal" },
        { L"유하린", L"에이, 너무 차갑다. 그냥 나랑 하고 싶었다고 해도 되는데.", L"school_day", L"yuharin_normal" },
        { L"{PLAYER}", L"그런 말 안 했어.", L"school_day", L"yuharin_normal" },
        { L"유하린", L"안 했으니까 내가 대신 해주는 거지.", L"school_day", L"yuharin_normal" },
        { L"", L"하린은 활동지를 {PLAYER} 쪽으로 반쯤 밀어놓았다.", L"school_day", L"yuharin_normal" },
        { L"유하린", L"자, 역할 분담하자. 너는 글씨 쓰기, 나는 옆에서 응원하기.", L"school_day", L"yuharin_normal" },
        { L"{PLAYER}", L"그건 역할 분담이 아니라 떠넘기기잖아.", L"school_day", L"yuharin_normal" },
        { L"유하린", L"들켰네.", L"school_day", L"yuharin_normal" },
        { L"", L"{PLAYER}는 한숨을 쉬었지만, 이상하게 기분이 나쁘지는 않았다.", L"school_day", L"yuharin_normal" },
        { L"유하린", L"근데 {PLAYER}야.", L"school_day", L"yuharin_normal" },
        { L"{PLAYER}", L"왜?", L"school_day", L"yuharin_normal" },
        { L"유하린", L"오늘은 어제보다 표정 좀 낫다.", L"school_day", L"yuharin_smile" },
        { L"{PLAYER}", L"……그래?", L"school_day", L"yuharin_normal" },
        { L"유하린", L"응. 살아있는 사람 같아졌어.", L"school_day", L"yuharin_smile" },
        { L"", L"장난스러운 말투였지만, 하린의 시선은 의외로 진지했다.", L"school_day", L"yuharin_normal" },
        { L"노트", L"유하린과의 시간이 조금 가까워졌다.", L"school_day", L"yuharin_normal" },
        { L"시스템", L"유하린 선택 횟수가 증가했습니다.", L"school_day", L"yuharin_normal" },
        { L"", L"수업이 끝나고, {PLAYER}는 가방 속 검은 노트를 펼쳤다." },
        { L"노트", L"첫 번째 선택이 기록되었다." },
        { L"노트", L"작은 선택은 작은 변화를 만들고, 작은 변화는 봄의 방향을 바꾼다." },
        { L"{PLAYER}", L"이런 식으로…… 앞으로 나아가라는 건가." },
        { L"", L"{PLAYER}는 노트를 덮었다." },
        { L"", L"아직 모든 것을 이해한 것은 아니었다." },
        { L"", L"하지만 한 가지는 분명했다." },
        { L"", L"이제 {PLAYER}의 하루는, 선택에 따라 조금씩 달라지고 있었다.", L"", L"", L"", L"stop"}
    };

    storyScripts[0][2] =
    {
        { L"", L"다음 날, 교실은 평소보다 조금 소란스러웠다.", L"school_day", L"", L"", L"story2.1"},
        { L"담임", L"오늘은 둘씩 짝을 지어서 활동지를 작성할 거다.",L"school_day" },
        { L"{PLAYER}", L"짝 활동……",L"school_day" },
        { L"", L"{PLAYER}는 조용히 빈자리를 찾았다.",L"school_day" },
        { L"", L"그 순간, 검은 노트가 가방 안에서 희미하게 떨렸다.",L"school_day" },
        { L"노트", L"선택은 관계를 만들고, 관계는 시간을 움직인다.",L"school_day" },
        { L"{PLAYER}", L"이번에도…… 누군가와 가까워져야 하는 건가.",L"school_day" },
        { L"", L"{PLAYER}의 시선 끝에 세 사람이 보였다.",L"school_day" },
        { L"", L"창가 쪽에서 손을 흔드는 유하린.",L"school_day" },
        { L"", L"앞자리에서 자료를 정리하고 있는 한세아." ,L"school_day"},
        { L"", L"교실 뒤쪽에서 조용히 책을 덮는 서이린." ,L"school_day"},
        { L"시스템", L"누구 옆에 앉을까?",L"school_day" },
        { L"{PLAYER}", L"여기 앉아도 돼?", L"school_day", L"seoirin_normal" },
        { L"서이린", L"……", L"school_day", L"seoirin_normal" },
        { L"{PLAYER}", L"싫으면 다른 데 갈게.", L"school_day", L"seoirin_normal" },
        { L"서이린", L"아니요. 앉아도 돼요.", L"school_day", L"seoirin_smile" },
        { L"", L"이린은 읽고 있던 책을 조용히 덮었다.", L"school_day", L"seoirin_normal" },
        { L"{PLAYER}", L"수업 중에도 책 읽는구나.", L"school_day", L"seoirin_normal" },
        { L"서이린", L"수업이 시작되기 전까지만요.", L"school_day", L"seoirin_normal" },
        { L"{PLAYER}", L"그 책…… 문예부 문집이야?", L"school_day", L"seoirin_normal" },
        { L"서이린", L"비슷해요.", L"school_day", L"seoirin_normal" },
        { L"{PLAYER}", L"비슷하다는 건 뭐야?", L"school_day", L"seoirin_normal" },
        { L"서이린", L"기록에 가까워요.", L"school_day", L"seoirin_normal" },
        { L"{PLAYER}", L"기록?", L"school_day", L"seoirin_normal" },
        { L"", L"이린은 바로 대답하지 않고 활동지 위에 이름을 적었다.", L"school_day", L"seoirin_normal" },
        { L"서이린", L"{PLAYER} 씨는 기록을 믿어요?", L"school_day", L"seoirin_normal" },
        { L"{PLAYER}", L"갑자기?", L"school_day", L"seoirin_normal" },
        { L"서이린", L"사람은 자주 잊으니까요. 적어두지 않으면, 있었던 일도 없던 일이 돼요.", L"school_day", L"seoirin_normal" },
        { L"", L"그 말에 {PLAYER}는 자신도 모르게 검은 노트를 떠올렸다.", L"school_day", L"seoirin_normal" },
        { L"{PLAYER}", L"……그럴지도 모르겠네.", L"school_day", L"seoirin_normal" },
        { L"서이린", L"그럼 오늘은 잊지 않게 적어둬요.", L"school_day", L"seoirin_normal" },
        { L"", L"이린은 조용히 활동지를 {PLAYER} 쪽으로 밀었다.", L"school_day", L"seoirin_normal" },
        { L"노트", L"서이린과의 시간이 조금 가까워졌다.", L"school_day", L"seoirin_normal" },
        { L"시스템", L"서이린 선택 횟수가 증가했습니다.", L"school_day", L"seoirin_normal" },
        { L"", L"수업이 끝나고, {PLAYER}는 가방 속 검은 노트를 펼쳤다." },
        { L"노트", L"첫 번째 선택이 기록되었다." },
        { L"노트", L"작은 선택은 작은 변화를 만들고, 작은 변화는 봄의 방향을 바꾼다." },
        { L"{PLAYER}", L"이런 식으로…… 앞으로 나아가라는 건가." },
        { L"", L"{PLAYER}는 노트를 덮었다." },
        { L"", L"아직 모든 것을 이해한 것은 아니었다." },
        { L"", L"하지만 한 가지는 분명했다." },
        { L"", L"이제 {PLAYER}의 하루는, 선택에 따라 조금씩 달라지고 있었다.", L"", L"", L"", L"stop"}
    };

    storyScripts[1][0] =
    {
        { L"", L"수업이 끝나고, 교실은 금세 소란스러워졌다.", L"", L"", L"", L"story3.1"},
        { L"", L"학생들은 매점으로, 동아리방으로, 운동장으로 흩어졌다.", L"school_hallway", L"" },
        { L"{PLAYER}", L"오늘은 그냥 집에 가도 되는 건가……" },
        { L"", L"그 순간, 가방 안의 검은 노트가 희미하게 떨렸다." },
        { L"노트", L"혼자 남는 순간, 봄은 다시 시작된다." },
        { L"{PLAYER}", L"그래. 아직 끝난 게 아니었지." },
        { L"", L"{PLAYER}는 복도에 서서 주변을 둘러보았다.", L"school_hallway", L"" },
        { L"", L"매점 쪽으로 걸어가는 유하린." },
        { L"", L"학생회실 방향으로 서류를 들고 가는 한세아." },
        { L"", L"도서관 쪽 복도에서 조용히 사라지는 서이린.", L"school_hallway", L"" },
        { L"시스템", L"방과 후, 누구와 시간을 보낼까?" },
        { L"{PLAYER}", L"한세아.", L"hansea_room", L"hansea_normal" },
        { L"한세아", L"{PLAYER}? 무슨 일이야?", L"hansea_room", L"hansea_normal" },
        { L"{PLAYER}", L"서류 많아 보이길래. 도와줄까 해서.", L"school_hallway", L"hansea_normal" },
        { L"한세아", L"괜찮아. 혼자 할 수 있어.", L"hansea_room", L"hansea_smile" },
        { L"{PLAYER}", L"그 말, 지난번에도 들은 것 같은데.", L"hansea_room", L"hansea_normal" },
        { L"한세아", L"……", L"hansea_room", L"hansea_normal" },
        { L"{PLAYER}", L"혼자 할 수 있는 거랑, 혼자 해야 하는 건 다르잖아.", L"hansea_room", L"hansea_normal" },
        { L"", L"세아는 잠시 {PLAYER}를 바라보았다.", L"hansea_room", L"hansea_normal" },
        { L"한세아", L"그렇게 말하면 거절하기 어렵네.", L"hansea_room", L"hansea_normal" },
        { L"{PLAYER}", L"그럼 성공이네.", L"hansea_room", L"hansea_normal" },
        { L"한세아", L"좋아. 학생회실로 와.", L"hansea_room", L"hansea_smile" },
        { L"", L"학생회실 책상 위에는 동아리 폐부 관련 서류가 가지런히 쌓여 있었다.", L"room", L"hansea_normal" },
        { L"{PLAYER}", L"이걸 다 오늘 해야 해?", L"hansea_room", L"hansea_normal" },
        { L"한세아", L"원래는 어제 끝냈어야 했어.", L"hansea_room", L"hansea_normal" },
        { L"{PLAYER}", L"그럼 더 문제잖아.", L"hansea_room", L"hansea_normal" },
        { L"한세아", L"그래서 지금 하고 있잖아.", L"hansea_room", L"hansea_normal" },
        { L"{PLAYER}", L"너 진짜 쉬는 법 모르지?", L"hansea_room", L"hansea_normal" },
        { L"한세아", L"쉬는 건 일이 끝난 다음에 해도 돼.", L"hansea_room", L"hansea_normal" },
        { L"{PLAYER}", L"그러다 네가 먼저 끝나겠다.", L"hansea_room", L"hansea_normal" },
        { L"한세아", L"……그런 말은 처음 들어.", L"hansea_room", L"hansea_normal" },
        { L"{PLAYER}", L"보통은 안 해?", L"hansea_room", L"hansea_normal" },
        { L"한세아", L"다들 내가 알아서 잘할 거라고 생각하니까.", L"hansea_room", L"hansea_normal" },
        { L"", L"세아는 아무렇지 않게 말했지만, 그 말끝은 조금 가라앉아 있었다.", L"hansea_room", L"hansea_normal" },
        { L"{PLAYER}", L"그럼 오늘은 나눠서 하자.", L"hansea_room", L"hansea_normal" },
        { L"한세아", L"응. 부탁할게.", L"hansea_room", L"hansea_smile" },
        { L"", L"세아는 서류 더미의 절반을 {PLAYER} 쪽으로 밀어주었다.", L"school_hallway", L"hansea_normal" },
        { L"한세아", L"고마워. 솔직히…… 조금 막막했어.", L"hansea_room", L"hansea_smile" },
        { L"{PLAYER}", L"그런 말도 할 줄 아네.", L"hansea_room", L"hansea_normal" },
        { L"한세아", L"나도 사람이니까.", L"hansea_room", L"hansea_normal" },
        { L"", L"그 말에 {PLAYER}는 잠깐 웃었다.", L"hansea_room", L"hansea_smile" },
        { L"노트", L"한세아와의 시간이 조금 더 가까워졌다.", L"hansea_room", L"hansea_normal" },
        { L"시스템", L"한세아 선택 횟수가 증가했습니다.", L"hansea_room", L"hansea_normal" },
        { L"", L"방과 후가 지나고, 학교 복도에는 학생들의 발소리가 거의 사라져 있었다.", L"school_hallway", L"" },
        { L"{PLAYER}", L"오늘도…… 넘어갈 수 있을까." },
        { L"", L"{PLAYER}는 가방 안의 검은 노트를 펼쳤다." },
        { L"노트", L"두 번째 선택이 기록되었다." },
        { L"노트", L"반복되는 봄은 아직 끝나지 않았다." },
        { L"노트", L"하지만 네가 선택한 시간은 사라지지 않는다." },
        { L"{PLAYER}", L"선택한 시간은 사라지지 않는다……" },
        { L"", L"{PLAYER}는 조용히 노트를 덮었다." },
        { L"", L"이제 그는 조금씩 알 것 같았다." },
        { L"", L"이 봄을 끝내는 방법은, 누군가의 마음에 가까워지는 것이라는 걸." }
    };

    storyScripts[1][1] =
    {
        { L"", L"수업이 끝나고, 교실은 금세 소란스러워졌다.", L"", L"", L"", L"story3.1"},
        { L"", L"학생들은 매점으로, 동아리방으로, 운동장으로 흩어졌다.", L"school_hallway", L"" },
        { L"{PLAYER}", L"오늘은 그냥 집에 가도 되는 건가……" },
        { L"", L"그 순간, 가방 안의 검은 노트가 희미하게 떨렸다." },
        { L"노트", L"혼자 남는 순간, 봄은 다시 시작된다." },
        { L"{PLAYER}", L"그래. 아직 끝난 게 아니었지." },
        { L"", L"{PLAYER}는 복도에 서서 주변을 둘러보았다.", L"school_hallway", L"" },
        { L"", L"매점 쪽으로 걸어가는 유하린." },
        { L"", L"학생회실 방향으로 서류를 들고 가는 한세아." },
        { L"", L"도서관 쪽 복도에서 조용히 사라지는 서이린.", L"school_hallway", L"" },
        { L"시스템", L"방과 후, 누구와 시간을 보낼까?" },
        { L"{PLAYER}", L"유하린.", L"school_day", L"yuharin_normal" },
        { L"유하린", L"오, {PLAYER}. 먼저 말을 걸다니. 성장했네?", L"school_day", L"yuharin_normal" },
        { L"{PLAYER}", L"그 정도야?", L"school_day", L"yuharin_normal" },
        { L"유하린", L"응. 어제의 너였으면 교실 구석에서 식물처럼 있었을걸.", L"school_day", L"yuharin_normal" },
        { L"{PLAYER}", L"사람을 식물 취급하지 마.", L"school_day", L"yuharin_normal" },
        { L"유하린", L"그럼 오늘은 인간답게 매점이나 가자.", L"school_day", L"yuharin_normal" },
        { L"", L"하린은 자연스럽게 {PLAYER}의 팔을 잡아끌었다.", L"school_day", L"yuharin_normal" },
        { L"{PLAYER}", L"잠깐, 나 간다고 안 했는데.", L"school_day", L"yuharin_normal" },
        { L"유하린", L"말 안 해도 얼굴에 쓰여 있었어. ‘저는 매점에 가고 싶습니다’라고.", L"school_day", L"yuharin_normal" },
        { L"{PLAYER}", L"그런 얼굴 안 했어.", L"school_day", L"yuharin_normal" },
        { L"유하린", L"그럼 지금부터 하면 돼.", L"school_day", L"yuharin_normal" },
        { L"", L"매점 앞은 학생들로 붐볐다.", L"school_day", L"yuharin_normal" },
        { L"유하린", L"{PLAYER}야, 너는 무슨 빵 좋아해?", L"school_day", L"yuharin_smile" },
        { L"{PLAYER}", L"아무거나.", L"school_day", L"yuharin_normal" },
        { L"유하린", L"아무거나 금지. 인생을 그렇게 대충 살면 재미없어.", L"school_day", L"yuharin_smile" },
        { L"{PLAYER}", L"빵 고르는 걸로 인생까지 가는 거야?", L"school_day", L"yuharin_normal" },
        { L"유하린", L"당연하지. 작은 선택이 인생을 바꾸는 법이야.", L"school_day", L"yuharin_normal" },
        { L"", L"{PLAYER}는 순간 검은 노트를 떠올렸다.", L"school_day", L"yuharin_normal" },
        { L"{PLAYER}", L"작은 선택……", L"school_day", L"yuharin_normal" },
        { L"유하린", L"왜 또 진지해졌어?", L"school_day", L"yuharin_normal" },
        { L"{PLAYER}", L"그냥. 네 말이 맞는 것 같아서.", L"school_day", L"yuharin_normal" },
        { L"유하린", L"뭐야, 갑자기 인정하니까 재미없네.", L"school_day", L"yuharin_smile" },
        { L"", L"하린은 웃으며 빵 하나를 {PLAYER} 손에 쥐여줬다.", L"school_day", L"yuharin_smile" },
        { L"유하린", L"자. 오늘의 선택은 이거야.", L"school_day", L"yuharin_normal" },
        { L"{PLAYER}", L"내 선택이 아닌 것 같은데.", L"school_day", L"yuharin_normal" },
        { L"유하린", L"내가 고른 걸 네가 받아들였으니까, 공동 선택이지.", L"school_day", L"yuharin_normal" },
        { L"", L"장난스러운 말이었지만, {PLAYER}는 이상하게 그 말이 오래 남았다.", L"school_day", L"yuharin_normal" },
        { L"노트", L"유하린과의 시간이 조금 더 가까워졌다.", L"school_day", L"yuharin_normal" },
        { L"시스템", L"유하린 선택 횟수가 증가했습니다.", L"school_day", L"yuharin_normal" },
        { L"", L"방과 후가 지나고, 학교 복도에는 학생들의 발소리가 거의 사라져 있었다.", L"school_hallway", L"" },
        { L"{PLAYER}", L"오늘도…… 넘어갈 수 있을까." },
        { L"", L"{PLAYER}는 가방 안의 검은 노트를 펼쳤다." },
        { L"노트", L"두 번째 선택이 기록되었다." },
        { L"노트", L"반복되는 봄은 아직 끝나지 않았다." },
        { L"노트", L"하지만 네가 선택한 시간은 사라지지 않는다." },
        { L"{PLAYER}", L"선택한 시간은 사라지지 않는다……" },
        { L"", L"{PLAYER}는 조용히 노트를 덮었다." },
        { L"", L"이제 그는 조금씩 알 것 같았다." },
        { L"", L"이 봄을 끝내는 방법은, 누군가의 마음에 가까워지는 것이라는 걸." }
    };

    storyScripts[1][2] =
    {
        { L"", L"수업이 끝나고, 교실은 금세 소란스러워졌다.", L"", L"", L"", L"story3.1"},
        { L"", L"학생들은 매점으로, 동아리방으로, 운동장으로 흩어졌다.", L"school_hallway", L"" },
        { L"{PLAYER}", L"오늘은 그냥 집에 가도 되는 건가……" },
        { L"", L"그 순간, 가방 안의 검은 노트가 희미하게 떨렸다." },
        { L"노트", L"혼자 남는 순간, 봄은 다시 시작된다." },
        { L"{PLAYER}", L"그래. 아직 끝난 게 아니었지." },
        { L"", L"{PLAYER}는 복도에 서서 주변을 둘러보았다.", L"school_hallway", L"" },
        { L"", L"매점 쪽으로 걸어가는 유하린." },
        { L"", L"학생회실 방향으로 서류를 들고 가는 한세아." },
        { L"", L"도서관 쪽 복도에서 조용히 사라지는 서이린.", L"school_hallway", L"" },
        { L"시스템", L"방과 후, 누구와 시간을 보낼까?" },
        { L"{PLAYER}", L"서이린.", L"library_day", L"seoirin_normal" },
        { L"서이린", L"……", L"library_day", L"seoirin_normal" },
        { L"{PLAYER}", L"도서관 가는 거야?", L"library_day", L"seoirin_normal" },
        { L"서이린", L"네.", L"library_day", L"seoirin_normal" },
        { L"{PLAYER}", L"같이 가도 돼?", L"library_day", L"seoirin_normal" },
        { L"서이린", L"도서관은 제 것이 아니니까요.", L"library_day", L"seoirin_normal" },
        { L"{PLAYER}", L"그건 허락이야, 거절이야?", L"library_day", L"seoirin_normal" },
        { L"서이린", L"따라오고 싶으면 따라와도 된다는 뜻이에요.", L"library_day", L"seoirin_normal" },
        { L"", L"이린은 그렇게 말하고 조용히 걸음을 옮겼다.", L"library_day", L"seoirin_normal" },
        { L"", L"도서관은 방과 후의 소란과 동떨어진 곳처럼 조용했다.", L"library_day", L"seoirin_normal" },
        { L"{PLAYER}", L"너는 매일 여기 와?", L"library_day", L"seoirin_normal" },
        { L"서이린", L"거의요.", L"library_day", L"seoirin_normal" },
        { L"{PLAYER}", L"책을 좋아해서?", L"library_day", L"seoirin_normal" },
        { L"서이린", L"잊지 않으려고요.", L"library_day", L"seoirin_normal" },
        { L"{PLAYER}", L"그 말, 전에도 했던 것 같은데.", L"library_day", L"seoirin_normal" },
        { L"서이린", L"그랬나요?", L"library_day", L"seoirin_normal" },
        { L"{PLAYER}", L"응. 기억하려고 책을 본다고.", L"library_day", L"seoirin_normal" },
        { L"", L"이린은 책장 앞에서 걸음을 멈췄다.", L"library_day", L"seoirin_normal" },
        { L"서이린", L"{PLAYER} 씨는 기억하고 싶은 게 있어요?", L"library_day", L"seoirin_normal" },
        { L"{PLAYER}", L"갑자기?", L"library_day", L"seoirin_normal" },
        { L"서이린", L"기억하고 싶은 게 없으면, 사람은 쉽게 흘려보내니까요.", L"library_day", L"seoirin_normal" },
        { L"{PLAYER}", L"나는……", L"library_day", L"seoirin_normal" },
        { L"", L"{PLAYER}는 검은 노트와 반복되는 하루를 떠올렸다.", L"library_day", L"seoirin_normal" },
        { L"{PLAYER}", L"잊으면 안 되는 게 생긴 것 같아.", L"library_day", L"seoirin_normal" },
        { L"서이린", L"그럼 적어두는 게 좋아요.", L"library_day", L"seoirin_smile" },
        { L"{PLAYER}", L"노트에?", L"library_day", L"seoirin_normal" },
        { L"서이린", L"네. 노트는 거짓말을 잘 안 하니까요.", L"library_day", L"seoirin_normal" },
        { L"", L"{PLAYER}는 가방 안의 검은 노트를 의식했다.", L"library_day", L"seoirin_normal" },
        { L"{PLAYER}", L"너, 그 노트에 대해 뭔가 아는 거야?", L"library_day", L"seoirin_normal" },
        { L"서이린", L"아직은 모르는 편이 좋아요.", L"library_day", L"seoirin_smile" },
        { L"{PLAYER}", L"왜 항상 그렇게 애매하게 말해?", L"library_day", L"seoirin_normal" },
        { L"서이린", L"확실하게 말하면, 사라지는 것들이 있으니까요.", L"library_day", L"seoirin_normal" },
        { L"", L"이린은 책 한 권을 꺼내 {PLAYER}에게 건넸다.", L"library_day", L"seoirin_normal" },
        { L"서이린", L"오늘은 이 책만 읽어봐요.", L"library_day", L"seoirin_normal" },
        { L"{PLAYER}", L"무슨 책인데?", L"library_day", L"seoirin_normal" },
        { L"서이린", L"봄이 끝나지 않는 사람들에 대한 기록이에요.", L"library_day", L"seoirin_normal" },
        { L"", L"{PLAYER}는 책 표지를 바라보았다.", L"library_day", L"seoirin_normal" },
        { L"", L"제목 없는 낡은 문집이었다.", L"library_day", L"seoirin_normal" },
        { L"노트", L"서이린과의 시간이 조금 더 가까워졌다.", L"library_day", L"seoirin_normal" },
        { L"시스템", L"서이린 선택 횟수가 증가했습니다.", L"library_day", L"seoirin_normal" },
        { L"", L"방과 후가 지나고, 학교 복도에는 학생들의 발소리가 거의 사라져 있었다.", L"school_hallway", L"" },
        { L"{PLAYER}", L"오늘도…… 넘어갈 수 있을까." },
        { L"", L"{PLAYER}는 가방 안의 검은 노트를 펼쳤다." },
        { L"노트", L"두 번째 선택이 기록되었다." },
        { L"노트", L"반복되는 봄은 아직 끝나지 않았다." },
        { L"노트", L"하지만 네가 선택한 시간은 사라지지 않는다." },
        { L"{PLAYER}", L"선택한 시간은 사라지지 않는다……" },
        { L"", L"{PLAYER}는 조용히 노트를 덮었다." },
        { L"", L"이제 그는 조금씩 알 것 같았다." },
        { L"", L"이 봄을 끝내는 방법은, 누군가의 마음에 가까워지는 것이라는 걸." }
    };

    storyScripts[2][0] =
    {
        { L"", L"방과 후가 되자 갑자기 비가 내리기 시작했다.", L"", L"", L"", L"story4.1"},
        { L"", L"교실 창문을 두드리는 빗소리가 복도까지 희미하게 번졌다.", L"school_hallway", L"" },
        { L"{PLAYER}", L"우산…… 안 가져왔는데." },
        { L"", L"{PLAYER}는 가방 안의 검은 노트를 펼쳤다." },
        { L"노트", L"비가 내리는 날에는 숨겨둔 마음이 조금씩 번진다." },
        { L"{PLAYER}", L"숨겨둔 마음……" },
        { L"", L"{PLAYER}는 복도 너머를 바라보았다.", L"school_hallway", L"" },
        { L"", L"창가에서 비를 바라보는 유하린." },
        { L"", L"학생회실 앞에서 젖은 서류를 정리하는 한세아." },
        { L"", L"도서관 입구에서 조용히 책을 안고 있는 서이린." },
        { L"시스템", L"비 오는 방과 후, 누구와 함께 있을까?" },
        { L"{PLAYER}", L"한세아.", L"hansea_room", L"hansea_normal" },
        { L"한세아", L"{PLAYER}? 아직 안 갔어?", L"hansea_room", L"hansea_normal" },
        { L"{PLAYER}", L"우산이 없어서. 너는?", L"hansea_room", L"hansea_normal" },
        { L"한세아", L"학생회 자료가 조금 젖어서 정리하고 있었어.", L"hansea_room", L"hansea_normal" },
        { L"", L"세아의 책상 위에는 물기가 묻은 서류들이 펼쳐져 있었다.", L"school_hallway", L"hansea_normal" },
        { L"{PLAYER}", L"이걸 혼자 다 하고 있었어?", L"hansea_room", L"hansea_normal" },
        { L"한세아", L"내가 맡은 일이니까.", L"hansea_room", L"hansea_normal" },
        { L"{PLAYER}", L"또 그 말이네.", L"hansea_room", L"hansea_normal" },
        { L"한세아", L"뭐가?", L"hansea_room", L"hansea_normal" },
        { L"{PLAYER}", L"“해야 하니까.” “맡은 일이니까.” 너는 맨날 그렇게 말하잖아.", L"hansea_room", L"hansea_normal" },
        { L"한세아", L"틀린 말은 아니야.", L"hansea_room", L"hansea_normal" },
        { L"{PLAYER}", L"틀린 말은 아닌데, 힘든 말이긴 하지.", L"hansea_room", L"hansea_normal" },
        { L"", L"세아는 잠시 손을 멈췄다.", L"hansea_room", L"hansea_normal" },
        { L"한세아", L"힘들어 보여?", L"hansea_room", L"hansea_normal" },
        { L"{PLAYER}", L"조금.", L"hansea_room", L"hansea_normal" },
        { L"한세아", L"나는 괜찮아 보여야 해.", L"hansea_room", L"hansea_smile" },
        { L"{PLAYER}", L"왜?", L"hansea_room", L"hansea_normal" },
        { L"한세아", L"학생회장이니까. 내가 흔들리면 다른 사람도 불안해하잖아.", L"hansea_room", L"hansea_normal" },
        { L"{PLAYER}", L"그럼 너는 누가 챙겨주는데?", L"hansea_room", L"hansea_normal" },
        { L"한세아", L"……", L"hansea_room", L"hansea_normal" },
        { L"", L"세아는 대답하지 않았다.", L"hansea_room", L"hansea_normal" },
        { L"", L"빗소리만 조용히 학생회실 창문을 두드렸다.", L"hansea_room", L"hansea_normal" },
        { L"{PLAYER}", L"일단 이쪽 서류부터 말리자. 혼자 하면 오래 걸리잖아.", L"school_hallway", L"hansea_normal" },
        { L"한세아", L"정말 도와줄 거야?", L"hansea_room", L"hansea_normal" },
        { L"{PLAYER}", L"이미 앉았잖아.", L"hansea_room", L"hansea_normal" },
        { L"한세아", L"고마워.", L"hansea_room", L"hansea_smile" },
        { L"", L"세아는 작게 숨을 내쉬었다.", L"hansea_room", L"hansea_normal" },
        { L"한세아", L"조금만…… 부탁할게.", L"hansea_room", L"hansea_smile" },
        { L"", L"그 말은 처음보다 훨씬 작고 솔직하게 들렸다.", L"hansea_room", L"hansea_normal" },
        { L"노트", L"한세아와의 시간이 더 깊어졌다.", L"hansea_room", L"hansea_normal" },
        { L"시스템", L"한세아 선택 횟수가 증가했습니다.", L"hansea_room", L"hansea_normal" },
        { L"", L"비는 한참이 지나서야 그쳤다." },
        { L"", L"젖은 운동장 위로 희미한 노을이 비쳤다." },
        { L"{PLAYER}", L"오늘도…… 조금 달라졌어." },
        { L"", L"{PLAYER}는 가방 속 검은 노트를 펼쳤다." },
        { L"노트", L"세 번째 선택이 기록되었다." },
        { L"노트", L"가까워질수록, 숨겨진 마음도 함께 드러난다." },
        { L"노트", L"하지만 모든 마음이 봄을 끝내고 싶어 하는 것은 아니다." },
        { L"{PLAYER}", L"끝내고 싶어 하지 않는 사람도 있다는 건가……" },
        { L"", L"{PLAYER}는 노트를 덮었다." },
        { L"", L"반복되는 봄의 끝이 가까워질수록, 세 사람의 비밀도 조금씩 모습을 드러내고 있었다." }
    };

    storyScripts[2][1] =
    {
        { L"", L"방과 후가 되자 갑자기 비가 내리기 시작했다.", L"", L"", L"", L"story4.1"},
        { L"", L"교실 창문을 두드리는 빗소리가 복도까지 희미하게 번졌다.", L"school_hallway", L"" },
        { L"{PLAYER}", L"우산…… 안 가져왔는데." },
        { L"", L"{PLAYER}는 가방 안의 검은 노트를 펼쳤다." },
        { L"노트", L"비가 내리는 날에는 숨겨둔 마음이 조금씩 번진다." },
        { L"{PLAYER}", L"숨겨둔 마음……" },
        { L"", L"{PLAYER}는 복도 너머를 바라보았다.", L"school_hallway", L"" },
        { L"", L"창가에서 비를 바라보는 유하린." },
        { L"", L"학생회실 앞에서 젖은 서류를 정리하는 한세아." },
        { L"", L"도서관 입구에서 조용히 책을 안고 있는 서이린." },
        { L"시스템", L"비 오는 방과 후, 누구와 함께 있을까?" },
        { L"{PLAYER}", L"유하린.", L"school_day", L"yuharin_normal" },
        { L"유하린", L"오, {PLAYER}. 우산 없지?", L"school_day", L"yuharin_normal" },
        { L"{PLAYER}", L"어떻게 알았어?", L"school_day", L"yuharin_normal" },
        { L"유하린", L"네 얼굴에 써 있어. “비상. 귀가 불가.” 이렇게.", L"school_day", L"yuharin_normal" },
        { L"{PLAYER}", L"내 얼굴은 대체 몇 줄까지 표시되는 거냐.", L"school_day", L"yuharin_normal" },
        { L"유하린", L"생각보다 정보량 많아.", L"school_day", L"yuharin_normal" },
        { L"", L"하린은 장난스럽게 웃으며 창밖을 바라보았다.", L"school_day", L"yuharin_smile" },
        { L"유하린", L"비 오면 이상하게 학교가 좀 낯설어 보이지 않아?", L"school_day", L"yuharin_normal" },
        { L"{PLAYER}", L"그런가?", L"school_day", L"yuharin_normal" },
        { L"유하린", L"응. 맨날 보던 운동장도, 복도도, 매점도 다 다른 곳 같아져.", L"school_hallway", L"yuharin_normal" },
        { L"{PLAYER}", L"너답지 않게 감성적이네.", L"school_day", L"yuharin_normal" },
        { L"유하린", L"나도 가끔은 분위기 잡거든?", L"school_day", L"yuharin_normal" },
        { L"{PLAYER}", L"진짜 가끔이긴 하다.", L"school_day", L"yuharin_normal" },
        { L"유하린", L"야.", L"school_day", L"yuharin_normal" },
        { L"", L"하린은 웃으며 {PLAYER}의 어깨를 가볍게 쳤다.", L"school_day", L"yuharin_smile" },
        { L"유하린", L"근데 말이야. 이런 날은 뭔가 기억에 오래 남을 것 같지 않아?", L"school_day", L"yuharin_normal" },
        { L"{PLAYER}", L"기억에?", L"school_day", L"yuharin_normal" },
        { L"유하린", L"응. 나중에 여길 떠나도, 이런 빗소리는 생각날 것 같아서.", L"school_day", L"yuharin_normal" },
        { L"{PLAYER}", L"떠나?", L"school_day", L"yuharin_normal" },
        { L"유하린", L"아니, 말이 그렇다는 거지.", L"school_day", L"yuharin_normal" },
        { L"", L"하린은 곧바로 웃으며 말을 돌렸다.", L"school_day", L"yuharin_smile" },
        { L"유하린", L"아무튼 우산 없으면 같이 쓰고 가자. 대신 네가 매점 빵 사기.", L"school_day", L"yuharin_smile" },
        { L"{PLAYER}", L"방금 감성적인 분위기 다 깨졌다.", L"school_day", L"yuharin_normal" },
        { L"유하린", L"그게 내 매력이지.", L"school_day", L"yuharin_normal" },
        { L"", L"{PLAYER}는 하린이 웃는 얼굴을 바라보았다.", L"school_day", L"yuharin_smile" },
        { L"", L"하지만 방금 그녀가 흘린 말이 이상하게 마음에 걸렸다.", L"school_day", L"yuharin_normal" },
        { L"노트", L"유하린과의 시간이 더 깊어졌다.", L"school_day", L"yuharin_normal" },
        { L"시스템", L"유하린 선택 횟수가 증가했습니다.", L"school_day", L"yuharin_normal" },
        { L"", L"비는 한참이 지나서야 그쳤다." },
        { L"", L"젖은 운동장 위로 희미한 노을이 비쳤다." },
        { L"{PLAYER}", L"오늘도…… 조금 달라졌어." },
        { L"", L"{PLAYER}는 가방 속 검은 노트를 펼쳤다." },
        { L"노트", L"세 번째 선택이 기록되었다." },
        { L"노트", L"가까워질수록, 숨겨진 마음도 함께 드러난다." },
        { L"노트", L"하지만 모든 마음이 봄을 끝내고 싶어 하는 것은 아니다." },
        { L"{PLAYER}", L"끝내고 싶어 하지 않는 사람도 있다는 건가……" },
        { L"", L"{PLAYER}는 노트를 덮었다." },
        { L"", L"반복되는 봄의 끝이 가까워질수록, 세 사람의 비밀도 조금씩 모습을 드러내고 있었다." }
    };

    storyScripts[2][2] =
    {
        { L"", L"방과 후가 되자 갑자기 비가 내리기 시작했다.", L"", L"", L"", L"story4.1"},
        { L"", L"교실 창문을 두드리는 빗소리가 복도까지 희미하게 번졌다.", L"school_hallway", L"" },
        { L"{PLAYER}", L"우산…… 안 가져왔는데." },
        { L"", L"{PLAYER}는 가방 안의 검은 노트를 펼쳤다." },
        { L"노트", L"비가 내리는 날에는 숨겨둔 마음이 조금씩 번진다." },
        { L"{PLAYER}", L"숨겨둔 마음……" },
        { L"", L"{PLAYER}는 복도 너머를 바라보았다.", L"school_hallway", L"" },
        { L"", L"창가에서 비를 바라보는 유하린." },
        { L"", L"학생회실 앞에서 젖은 서류를 정리하는 한세아." },
        { L"", L"도서관 입구에서 조용히 책을 안고 있는 서이린." },
        { L"시스템", L"비 오는 방과 후, 누구와 함께 있을까?" },
        { L"{PLAYER}", L"서이린.", L"library_day", L"seoirin_normal" },
        { L"서이린", L"비를 피하러 온 건가요?", L"library_day", L"seoirin_normal" },
        { L"{PLAYER}", L"반쯤은.", L"library_day", L"seoirin_normal" },
        { L"서이린", L"나머지 반은요?", L"library_day", L"seoirin_normal" },
        { L"{PLAYER}", L"네가 또 이상한 걸 알고 있을 것 같아서.", L"library_day", L"seoirin_normal" },
        { L"서이린", L"그건 좋은 이유는 아니네요.", L"library_day", L"seoirin_normal" },
        { L"{PLAYER}", L"그럼 나쁜 이유야?", L"library_day", L"seoirin_normal" },
        { L"서이린", L"위험한 이유에 가까워요.", L"library_day", L"seoirin_normal" },
        { L"", L"이린은 창가 자리에 앉아 낡은 책을 펼치고 있었다.", L"library_day", L"seoirin_normal" },
        { L"{PLAYER}", L"또 문예부 기록이야?", L"library_day", L"seoirin_normal" },
        { L"서이린", L"네. 사라지기 전에 읽어두려고요.", L"library_day", L"seoirin_normal" },
        { L"{PLAYER}", L"사라져?", L"library_day", L"seoirin_normal" },
        { L"서이린", L"기억하지 않는 기록은 오래 남지 않아요.", L"library_day", L"seoirin_normal" },
        { L"{PLAYER}", L"너는 왜 그렇게 기억에 집착해?", L"library_day", L"seoirin_normal" },
        { L"", L"이린은 책장을 넘기던 손을 멈췄다.", L"library_day", L"seoirin_normal" },
        { L"서이린", L"잊혀지는 건 조용해서요.", L"library_day", L"seoirin_normal" },
        { L"{PLAYER}", L"조용해서?", L"library_day", L"seoirin_normal" },
        { L"서이린", L"누군가 사라져도, 아무도 모르면 세상은 그대로 흘러가요.", L"library_day", L"seoirin_normal" },
        { L"", L"{PLAYER}는 아무 말도 하지 못했다.", L"library_day", L"seoirin_normal" },
        { L"서이린", L"그래서 기록해두는 거예요. 적어도 누군가는 있었다고.", L"library_day", L"seoirin_normal" },
        { L"{PLAYER}", L"그 누군가가…… 너야?", L"library_day", L"seoirin_normal" },
        { L"서이린", L"아직은 대답하지 않을게요.", L"library_day", L"seoirin_normal" },
        { L"{PLAYER}", L"항상 아직은이네.", L"library_day", L"seoirin_normal" },
        { L"서이린", L"아직이니까요.", L"library_day", L"seoirin_normal" },
        { L"", L"이린은 책 사이에서 작은 종이 조각을 꺼내 {PLAYER}에게 건넸다.", L"library_day", L"seoirin_normal" },
        { L"{PLAYER}", L"이건 뭐야?", L"library_day", L"seoirin_normal" },
        { L"서이린", L"비 오는 날에는 글자가 잘 번져요. 그러니까 사라지기 전에 읽어둬요.", L"library_day", L"seoirin_normal" },
        { L"", L"종이에는 희미한 문장이 적혀 있었다.", L"library_day", L"seoirin_normal" },
        { L"노트 조각", L"반복이 끝나는 날, 누군가는 기억에서 사라진다.", L"library_day", L"seoirin_normal" },
        { L"{PLAYER}", L"이게 무슨 뜻이야?", L"library_day", L"seoirin_normal" },
        { L"서이린", L"{PLAYER} 씨가 직접 알게 될 거예요.", L"library_day", L"seoirin_normal" },
        { L"", L"이린은 다시 책을 펼쳤다.", L"library_day", L"seoirin_normal" },
        { L"", L"빗소리 속에서, {PLAYER}는 처음으로 이 반복이 단순한 장난이 아닐지도 모른다고 생각했다.", L"library_day", L"seoirin_normal" },
        { L"노트", L"서이린과의 시간이 더 깊어졌다.", L"library_day", L"seoirin_normal" },
        { L"시스템", L"서이린 선택 횟수가 증가했습니다.", L"library_day", L"seoirin_normal" },
        { L"", L"비는 한참이 지나서야 그쳤다." },
        { L"", L"젖은 운동장 위로 희미한 노을이 비쳤다." },
        { L"{PLAYER}", L"오늘도…… 조금 달라졌어." },
        { L"", L"{PLAYER}는 가방 속 검은 노트를 펼쳤다." },
        { L"노트", L"세 번째 선택이 기록되었다." },
        { L"노트", L"가까워질수록, 숨겨진 마음도 함께 드러난다." },
        { L"노트", L"하지만 모든 마음이 봄을 끝내고 싶어 하는 것은 아니다." },
        { L"{PLAYER}", L"끝내고 싶어 하지 않는 사람도 있다는 건가……" },
        { L"", L"{PLAYER}는 노트를 덮었다." },
        { L"", L"반복되는 봄의 끝이 가까워질수록, 세 사람의 비밀도 조금씩 모습을 드러내고 있었다." }
    };

    storyScripts[3][0] =
    {
        { L"", L"방과 후, 학교에는 이상할 정도로 조용한 공기가 내려앉아 있었다.", L"", L"", L"", L"story5.1"},
        { L"", L"복도에는 학생들의 웃음소리가 남아 있었지만, {PLAYER}에게는 멀게만 들렸다.", L"school_hallway", L"" },
        { L"{PLAYER}", L"오늘은…… 뭔가 다르다." },
        { L"", L"{PLAYER}는 가방 안의 검은 노트를 꺼냈다." },
        { L"노트", L"네 번째 선택이 마지막 방향을 정한다." },
        { L"노트", L"가장 오래 바라본 마음이, 봄의 끝에서 너를 기다린다." },
        { L"{PLAYER}", L"마지막 방향……" },
        { L"", L"{PLAYER}는 천천히 복도 끝을 바라보았다.", L"school_hallway", L"" },
        { L"", L"교실에 남아 창밖을 보는 유하린." },
        { L"", L"학생회실에서 혼자 자료를 정리하는 한세아." },
        { L"", L"도서관 구석에서 오래된 책을 펼친 서이린." },
        { L"시스템", L"마지막 봄이 오기 전, 누구를 찾아갈까?" },
        { L"{PLAYER}", L"한세아.", L"hansea_room", L"hansea_normal" },
        { L"한세아", L"{PLAYER}? 아직 남아 있었어?", L"hansea_room", L"hansea_normal" },
        { L"{PLAYER}", L"너야말로. 아직도 일하는 거야?", L"hansea_room", L"hansea_normal" },
        { L"한세아", L"조금만 더 하면 끝나.", L"hansea_room", L"hansea_normal" },
        { L"{PLAYER}", L"그 “조금만”이 제일 오래 걸리는 말이던데.", L"hansea_room", L"hansea_normal" },
        { L"한세아", L"……부정하기 어렵네.", L"hansea_room", L"hansea_normal" },
        { L"", L"세아는 정리하던 서류를 가지런히 내려놓았다.", L"school_hallway", L"hansea_normal" },
        { L"{PLAYER}", L"너는 왜 그렇게 완벽하려고 해?", L"hansea_room", L"hansea_normal" },
        { L"한세아", L"완벽하면, 적어도 누군가를 실망시키지는 않으니까.", L"hansea_room", L"hansea_normal" },
        { L"{PLAYER}", L"근데 너는?", L"hansea_room", L"hansea_normal" },
        { L"한세아", L"나?", L"hansea_room", L"hansea_normal" },
        { L"{PLAYER}", L"너는 너 자신을 실망시키지 않으려고 너무 몰아붙이는 것 같아.", L"hansea_room", L"hansea_normal" },
        { L"", L"세아는 대답하지 못했다.", L"hansea_room", L"hansea_normal" },
        { L"", L"창밖의 노을이 학생회실 안으로 길게 들어왔다.", L"hansea_room", L"hansea_normal" },
        { L"한세아", L"나는 가끔 내가 멈추면 모든 게 무너질 것 같아.", L"hansea_room", L"hansea_normal" },
        { L"{PLAYER}", L"혼자 버틴다고 안 무너지는 건 아니야.", L"hansea_room", L"hansea_normal" },
        { L"한세아", L"그럼 어떻게 해야 해?", L"hansea_room", L"hansea_normal" },
        { L"{PLAYER}", L"같이 들면 되지. 무거운 건 나눠 들라고 있는 거니까.", L"hansea_room", L"hansea_normal" },
        { L"", L"세아는 한동안 {PLAYER}를 바라보았다.", L"hansea_room", L"hansea_normal" },
        { L"한세아", L"그 말…… 조금 위로된다.", L"hansea_room", L"hansea_normal" },
        { L"{PLAYER}", L"조금이면 충분해?", L"hansea_room", L"hansea_normal" },
        { L"한세아", L"지금은 충분해.", L"hansea_room", L"hansea_smile" },
        { L"노트", L"한세아와의 마지막 선택이 기록되었다.", L"hansea_room", L"hansea_normal" },
        { L"시스템", L"한세아 선택 횟수가 증가했습니다.", L"hansea_room", L"hansea_normal" },
        { L"", L"해가 완전히 저물고, 학교는 천천히 어둠에 잠겼다." },
        { L"", L"{PLAYER}는 복도 한가운데 멈춰 서서 검은 노트를 펼쳤다.", L"school_hallway", L"" },
        { L"노트", L"네 번째 선택이 기록되었다." },
        { L"노트", L"이제 봄은 마지막 장으로 향한다." },
        { L"노트", L"가장 많이 선택된 이름이, 마지막 선택지에 나타난다." },
        { L"{PLAYER}", L"결국 내가 골라온 시간이 답이 되는 건가." },
        { L"노트", L"선택은 사라지지 않는다." },
        { L"노트", L"네가 바라본 마음이, 너를 기다린다." },
        { L"", L"{PLAYER}는 노트를 조용히 덮었다." },
        { L"", L"반복되는 봄의 끝이 가까워지고 있었다." },
        { L"", L"그리고 다음 날, {PLAYER}는 마지막 선택 앞에 서게 된다." }
    };

    storyScripts[3][1] =
    {
        { L"", L"방과 후, 학교에는 이상할 정도로 조용한 공기가 내려앉아 있었다.", L"", L"", L"", L"story5.1"},
        { L"", L"복도에는 학생들의 웃음소리가 남아 있었지만, {PLAYER}에게는 멀게만 들렸다.", L"school_hallway", L"" },
        { L"{PLAYER}", L"오늘은…… 뭔가 다르다." },
        { L"", L"{PLAYER}는 가방 안의 검은 노트를 꺼냈다." },
        { L"노트", L"네 번째 선택이 마지막 방향을 정한다." },
        { L"노트", L"가장 오래 바라본 마음이, 봄의 끝에서 너를 기다린다." },
        { L"{PLAYER}", L"마지막 방향……" },
        { L"", L"{PLAYER}는 천천히 복도 끝을 바라보았다.", L"school_hallway", L"" },
        { L"", L"교실에 남아 창밖을 보는 유하린." },
        { L"", L"학생회실에서 혼자 자료를 정리하는 한세아." },
        { L"", L"도서관 구석에서 오래된 책을 펼친 서이린." },
        { L"시스템", L"마지막 봄이 오기 전, 누구를 찾아갈까?" },
        { L"{PLAYER}", L"유하린.", L"school_day", L"yuharin_normal" },
        { L"유하린", L"오, {PLAYER}. 이런 시간에 먼저 찾아오다니.", L"school_day", L"yuharin_normal" },
        { L"{PLAYER}", L"그냥 보여서.", L"school_day", L"yuharin_normal" },
        { L"유하린", L"그냥이라기엔 표정이 너무 진지한데?", L"school_day", L"yuharin_normal" },
        { L"{PLAYER}", L"너는 항상 웃고 있네.", L"school_day", L"yuharin_normal" },
        { L"유하린", L"그럼 울고 있을까?", L"school_day", L"yuharin_normal" },
        { L"{PLAYER}", L"가끔은 그래도 되지 않아?", L"school_day", L"yuharin_normal" },
        { L"", L"하린은 잠깐 말을 멈췄다.", L"school_day", L"yuharin_normal" },
        { L"유하린", L"너 가끔 이상한 타이밍에 정곡 찌른다.", L"school_day", L"yuharin_normal" },
        { L"{PLAYER}", L"그런가.", L"school_day", L"yuharin_normal" },
        { L"유하린", L"사람이 계속 웃는다고 해서, 계속 괜찮은 건 아니니까.", L"school_day", L"yuharin_smile" },
        { L"", L"하린은 창밖을 바라보며 작게 웃었다.", L"school_day", L"yuharin_smile" },
        { L"유하린", L"근데 그래도 나는 웃는 쪽이 좋아.", L"school_day", L"yuharin_smile" },
        { L"{PLAYER}", L"왜?", L"school_day", L"yuharin_normal" },
        { L"유하린", L"누가 기억해줄 때, 울던 얼굴보단 웃던 얼굴이면 좋잖아.", L"school_day", L"yuharin_normal" },
        { L"{PLAYER}", L"나는 둘 다 기억할 수 있을 것 같은데.", L"school_day", L"yuharin_normal" },
        { L"유하린", L"……치사하게 말 잘하네.", L"school_day", L"yuharin_normal" },
        { L"", L"하린은 평소처럼 장난스럽게 웃었지만, 그 웃음은 조금 느리게 번졌다.", L"school_day", L"yuharin_smile" },
        { L"유하린", L"그럼 오늘은 특별히 기억하기 좋은 얼굴로 있어줄게.", L"school_day", L"yuharin_normal" },
        { L"노트", L"유하린과의 마지막 선택이 기록되었다.", L"school_day", L"yuharin_normal" },
        { L"시스템", L"유하린 선택 횟수가 증가했습니다.", L"school_day", L"yuharin_normal" },
        { L"", L"해가 완전히 저물고, 학교는 천천히 어둠에 잠겼다." },
        { L"", L"{PLAYER}는 복도 한가운데 멈춰 서서 검은 노트를 펼쳤다.", L"school_hallway", L"" },
        { L"노트", L"네 번째 선택이 기록되었다." },
        { L"노트", L"이제 봄은 마지막 장으로 향한다." },
        { L"노트", L"가장 많이 선택된 이름이, 마지막 선택지에 나타난다." },
        { L"{PLAYER}", L"결국 내가 골라온 시간이 답이 되는 건가." },
        { L"노트", L"선택은 사라지지 않는다." },
        { L"노트", L"네가 바라본 마음이, 너를 기다린다." },
        { L"", L"{PLAYER}는 노트를 조용히 덮었다." },
        { L"", L"반복되는 봄의 끝이 가까워지고 있었다." },
        { L"", L"그리고 다음 날, {PLAYER}는 마지막 선택 앞에 서게 된다." }
    };

    storyScripts[3][2] =
    {
        { L"", L"방과 후, 학교에는 이상할 정도로 조용한 공기가 내려앉아 있었다.", L"", L"", L"", L"story5.1"},
        { L"", L"복도에는 학생들의 웃음소리가 남아 있었지만, {PLAYER}에게는 멀게만 들렸다.", L"school_hallway", L"" },
        { L"{PLAYER}", L"오늘은…… 뭔가 다르다." },
        { L"", L"{PLAYER}는 가방 안의 검은 노트를 꺼냈다." },
        { L"노트", L"네 번째 선택이 마지막 방향을 정한다." },
        { L"노트", L"가장 오래 바라본 마음이, 봄의 끝에서 너를 기다린다." },
        { L"{PLAYER}", L"마지막 방향……" },
        { L"", L"{PLAYER}는 천천히 복도 끝을 바라보았다.", L"school_hallway", L"" },
        { L"", L"교실에 남아 창밖을 보는 유하린." },
        { L"", L"학생회실에서 혼자 자료를 정리하는 한세아." },
        { L"", L"도서관 구석에서 오래된 책을 펼친 서이린." },
        { L"시스템", L"마지막 봄이 오기 전, 누구를 찾아갈까?" },
        { L"{PLAYER}", L"서이린.", L"library_day", L"seoirin_normal" },
        { L"서이린", L"도서관이 닫힐 시간이에요.", L"library_day", L"seoirin_normal" },
        { L"{PLAYER}", L"알아. 그래도 잠깐만.", L"library_day", L"seoirin_normal" },
        { L"서이린", L"무슨 일이에요?", L"library_day", L"seoirin_normal" },
        { L"{PLAYER}", L"너는 왜 항상 사라질 사람처럼 말해?", L"library_day", L"seoirin_normal" },
        { L"", L"이린은 책장을 넘기던 손을 멈췄다.", L"library_day", L"seoirin_normal" },
        { L"서이린", L"그렇게 들렸나요?", L"library_day", L"seoirin_normal" },
        { L"{PLAYER}", L"응. 꼭 누군가에게 기억되기만 바라는 사람처럼.", L"library_day", L"seoirin_normal" },
        { L"서이린", L"기억되는 건 쉬운 일이 아니에요.", L"library_day", L"seoirin_normal" },
        { L"{PLAYER}", L"잊히는 건?", L"library_day", L"seoirin_normal" },
        { L"서이린", L"더 쉬워요. 그래서 무서운 거예요.", L"library_day", L"seoirin_normal" },
        { L"", L"이린은 책 사이에 끼워둔 책갈피를 바라보았다.", L"library_day", L"seoirin_normal" },
        { L"서이린", L"사람은 생각보다 많은 걸 잊어요.", L"library_day", L"seoirin_normal" },
        { L"서이린", L"함께 걸은 복도, 나눈 말, 이름까지도.", L"school_hallway", L"seoirin_normal" },
        { L"{PLAYER}", L"그럼 다시 기억하면 되잖아.", L"library_day", L"seoirin_normal" },
        { L"서이린", L"잊은 걸 다시 기억하는 건, 처음부터 아는 것보다 어려워요.", L"library_day", L"seoirin_normal" },
        { L"{PLAYER}", L"그래도 나는 찾을 것 같아.", L"library_day", L"seoirin_normal" },
        { L"서이린", L"무엇을요?", L"library_day", L"seoirin_normal" },
        { L"{PLAYER}", L"잊으면 안 될 사람을.", L"library_day", L"seoirin_normal" },
        { L"", L"이린의 표정이 아주 조금 흔들렸다.", L"library_day", L"seoirin_normal" },
        { L"서이린", L"그 말은…… 위험한 약속이에요.", L"library_day", L"seoirin_normal" },
        { L"{PLAYER}", L"그래도 할게.", L"library_day", L"seoirin_normal" },
        { L"서이린", L"그럼 적어둘게요. {PLAYER} 씨가 그렇게 말했다고.", L"library_day", L"seoirin_normal" },
        { L"노트", L"서이린과의 마지막 선택이 기록되었다.", L"library_day", L"seoirin_normal" },
        { L"시스템", L"서이린 선택 횟수가 증가했습니다.", L"library_day", L"seoirin_normal" },
        { L"", L"해가 완전히 저물고, 학교는 천천히 어둠에 잠겼다." },
        { L"", L"{PLAYER}는 복도 한가운데 멈춰 서서 검은 노트를 펼쳤다.", L"school_hallway", L"" },
        { L"노트", L"네 번째 선택이 기록되었다." },
        { L"노트", L"이제 봄은 마지막 장으로 향한다." },
        { L"노트", L"가장 많이 선택된 이름이, 마지막 선택지에 나타난다." },
        { L"{PLAYER}", L"결국 내가 골라온 시간이 답이 되는 건가." },
        { L"노트", L"선택은 사라지지 않는다." },
        { L"노트", L"네가 바라본 마음이, 너를 기다린다." },
        { L"", L"{PLAYER}는 노트를 조용히 덮었다." },
        { L"", L"반복되는 봄의 끝이 가까워지고 있었다." },
        { L"", L"그리고 다음 날, {PLAYER}는 마지막 선택 앞에 서게 된다." }
    };

    // 최종 선택 화면 전에 노트가 마지막 이름을 보여주는 대사다.
    finalChoiceIntroStories[0] =
    {
        { L"", L"다음 날 방과 후, 학교는 이상할 정도로 조용했다.", L"school_hallway", L"" },
        { L"", L"복도에는 아무도 없었고, 창밖의 벚꽃잎만 천천히 흩날리고 있었다.", L"school_hallway", L"" },
        { L"{PLAYER}", L"드디어…… 마지막인가.", L"school_hallway", L"" },
        { L"", L"{PLAYER}는 가방에서 검은 노트를 꺼냈다.", L"school_hallway", L"" },
        { L"노트", L"네가 선택해온 시간이 마지막 이름을 불러낸다.", L"school_hallway", L"" },
        { L"노트", L"가장 많이 바라본 마음이, 봄의 끝에서 기다리고 있다.", L"school_hallway", L"" },
        { L"{PLAYER}", L"가장 많이 바라본 마음……", L"school_hallway", L"" },
        { L"", L"노트의 빈 페이지 위에 천천히 이름 하나가 떠올랐다.", L"school_hallway", L"" },
        { L"노트", L"한세아.", L"school_hallway", L"" },
        { L"{PLAYER}", L"세아……", L"school_hallway", L"" },
        { L"노트", L"완벽해 보이는 봄의 균열을 마주하겠습니까?", L"school_hallway", L"" },
        { L"시스템", L"한세아와 마지막 봄을 넘긴다.", L"school_hallway", L"" }
    };

    finalChoiceIntroStories[1] =
    {
        { L"", L"다음 날 방과 후, 학교는 이상할 정도로 조용했다.", L"school_hallway", L"" },
        { L"", L"복도에는 아무도 없었고, 창밖의 벚꽃잎만 천천히 흩날리고 있었다.", L"school_hallway", L"" },
        { L"{PLAYER}", L"드디어…… 마지막인가.", L"school_hallway", L"" },
        { L"", L"{PLAYER}는 가방에서 검은 노트를 꺼냈다.", L"school_hallway", L"" },
        { L"노트", L"네가 선택해온 시간이 마지막 이름을 불러낸다.", L"school_hallway", L"" },
        { L"노트", L"가장 많이 바라본 마음이, 봄의 끝에서 기다리고 있다.", L"school_hallway", L"" },
        { L"{PLAYER}", L"가장 많이 바라본 마음……", L"school_hallway", L"" },
        { L"", L"노트의 빈 페이지 위에 천천히 이름 하나가 떠올랐다.", L"school_hallway", L"" },
        { L"노트", L"유하린.", L"school_hallway", L"" },
        { L"{PLAYER}", L"하린……", L"school_hallway", L"" },
        { L"노트", L"웃음 뒤에 숨겨진 작별을 마주하겠습니까?", L"school_hallway", L"" },
        { L"시스템", L"유하린과 마지막 봄을 넘긴다.", L"school_hallway", L"" }
    };

    finalChoiceIntroStories[2] =
    {
        { L"", L"다음 날 방과 후, 학교는 이상할 정도로 조용했다.", L"school_hallway", L"" },
        { L"", L"복도에는 아무도 없었고, 창밖의 벚꽃잎만 천천히 흩날리고 있었다.", L"school_hallway", L"" },
        { L"{PLAYER}", L"드디어…… 마지막인가.", L"school_hallway", L"" },
        { L"", L"{PLAYER}는 가방에서 검은 노트를 꺼냈다.", L"school_hallway", L"" },
        { L"노트", L"네가 선택해온 시간이 마지막 이름을 불러낸다.", L"school_hallway", L"" },
        { L"노트", L"가장 많이 바라본 마음이, 봄의 끝에서 기다리고 있다.", L"school_hallway", L"" },
        { L"{PLAYER}", L"가장 많이 바라본 마음……", L"school_hallway", L"" },
        { L"", L"노트의 빈 페이지 위에 천천히 이름 하나가 떠올랐다.", L"school_hallway", L"" },
        { L"노트", L"서이린.", L"school_hallway", L"" },
        { L"{PLAYER}", L"이린……", L"school_hallway", L"" },
        { L"노트", L"기억하고 있는 봄의 끝을 마주하겠습니까?", L"school_hallway", L"" },
        { L"시스템", L"서이린과 마지막 봄을 넘긴다.", L"school_hallway", L"" }
    };

    finalChoiceIntroStories[3] =
    {
        { L"", L"다음 날 방과 후, 학교는 이상할 정도로 조용했다.", L"school_hallway", L"" },
        { L"", L"복도에는 아무도 없었고, 창밖의 벚꽃잎만 천천히 흩날리고 있었다.", L"school_hallway", L"" },
        { L"{PLAYER}", L"드디어…… 마지막인가.", L"school_hallway", L"" },
        { L"", L"{PLAYER}는 가방에서 검은 노트를 꺼냈다.", L"school_hallway", L"" },
        { L"노트", L"네가 선택해온 시간이 마지막 이름을 불러낸다.", L"school_hallway", L"" },
        { L"노트", L"가장 많이 바라본 마음이, 봄의 끝에서 기다리고 있다.", L"school_hallway", L"" },
        { L"{PLAYER}", L"가장 많이 바라본 마음……", L"school_hallway", L"" },
        { L"", L"노트의 빈 페이지 위에 천천히 이름 하나가 떠올랐다.", L"school_hallway", L"" },
        { L"", L"하지만 노트의 글자는 하나의 이름으로 고정되지 못했다.", L"school_day", L"" },
        { L"노트", L"마음이 충분히 닿지 않았다.", L"school_day", L"" },
        { L"노트", L"봄은 방향을 잃었다.", L"school_day", L"" },
        { L"{PLAYER}", L"방향을 잃었다고?", L"school_day", L"" },
        { L"", L"노트의 마지막 페이지가 스스로 찢어졌다.", L"school_day", L"" },
        { L"???", L"결정을 못 했네?", L"school_day", L"" },
        { L"{PLAYER}", L"누구야?", L"school_day", L"" },
        { L"시스템", L"새누와 숨겨진 봄으로 떨어진다.", L"school_day", L"" }
    };

    // 엔딩 대사다. 0 = Happy, 1 = Bad, 2 = Saenoo Hidden.
    endingStories[0][0] =
    {
        { L"", L"{PLAYER}는 학생회실 앞에서 세아를 발견했다.", L"hansea_room", L"hansea_normal" },
        { L"한세아", L"{PLAYER}? 연설 시간까지 얼마 안 남았어.", L"hansea_room", L"hansea_normal" },
        { L"{PLAYER}", L"그래서 온 거야.", L"hansea_room", L"hansea_normal" },
        { L"한세아", L"걱정하지 마. 대본은 다 외웠어. 실수하지 않을 거야.", L"hansea_room", L"hansea_normal" },
        { L"{PLAYER}", L"세아야.", L"hansea_room", L"hansea_normal" },
        { L"한세아", L"응?", L"hansea_room", L"hansea_normal" },
        { L"{PLAYER}", L"실수하지 않는 말보다, 네 진짜 말이 듣고 싶어.", L"hansea_room", L"hansea_normal" },
        { L"", L"세아는 대본을 쥔 손에 힘을 주었다.", L"hansea_room", L"hansea_normal" },
        { L"한세아", L"나는 완벽해야 해. 그래야 모두가 안심하니까.", L"hansea_room", L"hansea_normal" },
        { L"{PLAYER}", L"네가 완벽해서 좋은 게 아니야.", L"hansea_room", L"hansea_normal" },
        { L"한세아", L"……", L"hansea_room", L"hansea_normal" },
        { L"{PLAYER}", L"힘들어도 버티는 너를 봤어. 그러니까 이제는 혼자 버티지 않아도 돼.", L"hansea_room", L"hansea_normal" },
        { L"한세아", L"내가 부족해도…… 괜찮을까?", L"hansea_room", L"hansea_normal" },
        { L"{PLAYER}", L"응. 부족해도 한세아잖아.", L"hansea_room", L"hansea_normal" },
        { L"", L"세아는 천천히 대본을 접었다.", L"hansea_room", L"hansea_normal" },
        { L"한세아", L"그럼 오늘은…… 내가 하고 싶은 말을 해볼게.", L"hansea_room", L"hansea_smile" },
        { L"", L"연설장에 선 세아는 준비한 대본 대신 자신의 진심을 말했다.", L"hansea_room", L"hansea_normal" },
        { L"한세아", L"저는 사실 완벽한 사람이 아닙니다.", L"hansea_room", L"hansea_normal" },
        { L"한세아", L"하지만 이제는 부족한 저도 인정하고 싶습니다.", L"hansea_room", L"hansea_normal" },
        { L"", L"연설이 끝난 뒤, 세아는 옥상에서 {PLAYER}에게 조용히 웃었다.", L"hansea_room", L"hansea_smile" },
        { L"한세아", L"나를 완벽한 사람으로 봐주지 않아서 고마워.", L"hansea_room", L"hansea_smile" },
        { L"한세아", L"그냥 나로 봐줘서.", L"hansea_room", L"hansea_smile" },
        { L"노트", L"완벽하지 않은 봄이, 처음으로 내일을 맞이했다.", L"hansea_room", L"" },
        { L"엔딩 CG", L"노을진 옥상. 세아가 대본을 내려놓고 {PLAYER}를 향해 부드럽게 웃는다. 바람에 종이가 살짝 흩날린다.", L"hansea_room", L"hansea_smile" }
    };

    endingStories[0][1] =
    {
        { L"", L"{PLAYER}는 교실 창가에서 하린을 찾았다.", L"school_day", L"yuharin_normal" },
        { L"유하린", L"뭐야, {PLAYER}. 그런 얼굴로 오면 내가 진짜 떠나는 사람 같잖아.", L"school_day", L"yuharin_normal" },
        { L"{PLAYER}", L"떠나는 거 맞잖아.", L"school_day", L"yuharin_normal" },
        { L"유하린", L"……그렇긴 하지.", L"school_day", L"yuharin_normal" },
        { L"", L"하린은 평소처럼 웃었지만, 그 웃음은 조금 떨리고 있었다.", L"school_day", L"yuharin_smile" },
        { L"{PLAYER}", L"억지로 괜찮은 척 안 해도 돼.", L"school_day", L"yuharin_normal" },
        { L"유하린", L"나 괜찮은데?", L"school_day", L"yuharin_smile" },
        { L"{PLAYER}", L"아니. 안 괜찮아 보여.", L"school_day", L"yuharin_normal" },
        { L"유하린", L"……너 진짜 눈치 없는데, 가끔은 너무 정확해서 짜증 나.", L"school_day", L"yuharin_normal" },
        { L"{PLAYER}", L"가기 싫으면, 가기 싫다고 해도 돼.", L"school_day", L"yuharin_normal" },
        { L"유하린", L"나…… 진짜 가기 싫어.", L"school_day", L"yuharin_normal" },
        { L"", L"하린은 웃으려 했지만, 결국 눈물을 참지 못했다.", L"school_day", L"yuharin_normal" },
        { L"유하린", L"여기서 계속 장난치고, 매점 가고, 너 놀리고…… 그냥 그런 하루가 더 있었으면 좋겠어.", L"school_day", L"yuharin_normal" },
        { L"{PLAYER}", L"끝나는 게 아니야. 다음에 다시 이어지는 거야.", L"school_day", L"yuharin_normal" },
        { L"유하린", L"진짜?", L"school_day", L"yuharin_normal" },
        { L"{PLAYER}", L"응. 이번 봄이 끝나도, 너랑 나는 계속 이어질 거야.", L"school_day", L"yuharin_normal" },
        { L"유하린", L"치사하게 말 잘하네, {PLAYER}.", L"school_day", L"yuharin_smile" },
        { L"", L"하린은 울면서 웃었다.", L"school_day", L"yuharin_smile" },
        { L"노트", L"끝나지 않기를 바라던 봄은, 다시 만날 약속이 되었다.", L"school_day", L"" },
        { L"엔딩 CG", L"학교 앞. 하린이 눈물을 닦으며 웃고 있고, {PLAYER}는 옆에서 조용히 서 있다. 둘 사이로 벚꽃잎이 흩날린다.", L"school_day", L"yuharin_smile" }
    };

    endingStories[0][2] =
    {
        { L"", L"{PLAYER}는 도서관 가장 안쪽 서가에서 이린을 찾았다.", L"library_day", L"seoirin_normal" },
        { L"서이린", L"왔네요.", L"library_day", L"seoirin_normal" },
        { L"{PLAYER}", L"기다리고 있었어?", L"library_day", L"seoirin_normal" },
        { L"서이린", L"언젠가는 올 거라고 생각했어요.", L"library_day", L"seoirin_normal" },
        { L"{PLAYER}", L"이린아. 너는 뭘 알고 있는 거야?", L"library_day", L"seoirin_normal" },
        { L"서이린", L"이 봄이 끝나면, {PLAYER} 씨는 저를 잊게 돼요.", L"library_day", L"seoirin_normal" },
        { L"{PLAYER}", L"뭐?", L"library_day", L"seoirin_normal" },
        { L"서이린", L"괜찮아요. 이번에는 {PLAYER} 씨가 앞으로 가는 걸 보고 싶어요.", L"library_day", L"seoirin_normal" },
        { L"{PLAYER}", L"나는 괜찮지 않아.", L"library_day", L"seoirin_normal" },
        { L"서이린", L"기억하지 못하면 아프지도 않을 거예요.", L"library_day", L"seoirin_normal" },
        { L"{PLAYER}", L"잊어서 편한 것보다, 아파도 기억하는 쪽이 나아.", L"library_day", L"seoirin_normal" },
        { L"", L"이린의 표정이 아주 조금 흔들렸다.", L"library_day", L"seoirin_normal" },
        { L"서이린", L"그건 너무 이기적인 말이에요.", L"library_day", L"seoirin_normal" },
        { L"{PLAYER}", L"그래도 기억할게. 전부가 아니어도 돼. 조금이라도 남아 있으면 다시 찾을게.", L"library_day", L"seoirin_normal" },
        { L"서이린", L"{PLAYER} 씨는…… 이상한 사람이네요.", L"library_day", L"seoirin_normal" },
        { L"{PLAYER}", L"그건 자주 듣는 말이야.", L"library_day", L"seoirin_normal" },
        { L"", L"이린은 조용히 웃었다.", L"library_day", L"seoirin_smile" },
        { L"서이린", L"그럼 이걸 가져가요.", L"library_day", L"seoirin_smile" },
        { L"", L"이린은 낡은 책갈피를 {PLAYER}에게 건넸다.", L"library_day", L"seoirin_normal" },
        { L"서이린", L"혹시 잊어도, 다시 펼칠 수 있게.", L"library_day", L"seoirin_smile" },
        { L"노트", L"잊힌 봄은 책갈피가 되어, 다시 펼쳐졌다.", L"library_day", L"" },
        { L"엔딩 CG", L"도서관 창가. 이린이 책갈피를 건네고, {PLAYER}는 그것을 조심스럽게 받는다. 빛이 먼지 사이로 내려온다.", L"library_day", L"seoirin_smile" }
    };

    endingStories[1][0] =
    {
        { L"", L"{PLAYER}는 학생회실 앞에서 세아를 발견했다.", L"hansea_room", L"hansea_normal" },
        { L"한세아", L"이제 곧 연설 시간이야.", L"hansea_room", L"hansea_normal" },
        { L"{PLAYER}", L"긴장돼?", L"hansea_room", L"hansea_normal" },
        { L"한세아", L"괜찮아. 전부 준비했어.", L"hansea_room", L"hansea_normal" },
        { L"{PLAYER}", L"역시 학생회장이네.", L"hansea_room", L"hansea_normal" },
        { L"한세아", L"응. 실수하면 안 되니까.", L"hansea_room", L"hansea_normal" },
        { L"", L"세아는 완벽하게 웃었다.", L"hansea_room", L"hansea_smile" },
        { L"", L"연설장에서 세아는 단 한 번도 틀리지 않았다.", L"hansea_room", L"hansea_normal" },
        { L"", L"목소리도, 표정도, 손짓도 완벽했다.", L"hansea_room", L"hansea_normal" },
        { L"", L"모두가 박수를 보냈다.", L"hansea_room", L"hansea_normal" },
        { L"{PLAYER}", L"잘했어.", L"hansea_room", L"hansea_normal" },
        { L"한세아", L"고마워.", L"hansea_room", L"hansea_smile" },
        { L"", L"하지만 세아의 웃음은 어딘가 텅 비어 있었다.", L"hansea_room", L"hansea_normal" },
        { L"한세아", L"괜찮아. 원래 내가 해야 하는 일이니까.", L"hansea_room", L"hansea_normal" },
        { L"{PLAYER}", L"……", L"hansea_room", L"hansea_normal" },
        { L"", L"{PLAYER}는 그 말이 처음보다 더 차갑게 들린다는 것을 깨달았다.", L"hansea_room", L"hansea_normal" },
        { L"노트", L"봄은 끝났지만, 그녀는 여전히 완벽한 척 웃고 있었다.", L"hansea_room", L"" },
        { L"엔딩 CG", L"강당 뒤편. 세아가 박수 소리 속에서 완벽하게 웃고 있지만, 눈빛은 비어 있다. {PLAYER}는 멀리서 바라본다.", L"hansea_room", L"hansea_normal" }
    };

    endingStories[1][1] =
    {
        { L"", L"{PLAYER}는 교실 창가에서 하린을 찾았다.", L"school_day", L"yuharin_normal" },
        { L"유하린", L"{PLAYER}. 나 이제 진짜 간다?", L"school_day", L"yuharin_smile" },
        { L"{PLAYER}", L"응. 잘 가.", L"school_day", L"yuharin_normal" },
        { L"유하린", L"와, 너무 담백한 거 아니야?", L"school_day", L"yuharin_smile" },
        { L"{PLAYER}", L"네가 괜찮다고 했잖아.", L"school_day", L"yuharin_normal" },
        { L"유하린", L"그랬지. 나 완전 괜찮아.", L"school_day", L"yuharin_smile" },
        { L"", L"하린은 평소처럼 환하게 웃었다.", L"school_day", L"yuharin_smile" },
        { L"유하린", L"나 없다고 너무 심심해하지 말고.", L"school_day", L"yuharin_smile" },
        { L"{PLAYER}", L"너도 잘 지내.", L"school_day", L"yuharin_normal" },
        { L"유하린", L"응. 연락할게.", L"school_day", L"yuharin_smile" },
        { L"", L"버스가 출발했다.", L"school_hallway", L"" },
        { L"", L"{PLAYER}는 창문 너머로 하린을 바라보았다.", L"school_hallway", L"" },
        { L"", L"그 순간, 창문에 비친 하린의 얼굴이 보였다.", L"school_hallway", L"" },
        { L"", L"하린은 웃고 있지 않았다.", L"school_hallway", L"" },
        { L"{PLAYER}", L"……", L"school_hallway", L"" },
        { L"노트", L"웃음은 봄을 넘겼지만, 진심은 그곳에 남겨졌다.", L"school_hallway", L"" },
        { L"엔딩 CG", L"버스 창문 너머 하린이 고개를 숙이고 있다. {PLAYER}는 멀리서 버스를 바라본다. 화면은 차갑고 흐린 톤.", L"school_hallway", L"" }
    };

    endingStories[1][2] =
    {
        { L"", L"{PLAYER}는 도서관 가장 안쪽 서가에서 이린을 찾았다.", L"library_day", L"seoirin_normal" },
        { L"서이린", L"왔네요.", L"library_day", L"seoirin_normal" },
        { L"{PLAYER}", L"너, 이제 말해줄 수 있어?", L"library_day", L"seoirin_normal" },
        { L"서이린", L"이 봄이 끝나면, {PLAYER} 씨는 저를 잊게 돼요.", L"library_day", L"seoirin_normal" },
        { L"{PLAYER}", L"그게 무슨 말이야?", L"library_day", L"seoirin_normal" },
        { L"서이린", L"괜찮아요. {PLAYER} 씨는 앞으로 가면 돼요.", L"library_day", L"seoirin_normal" },
        { L"{PLAYER}", L"하지만 너는?", L"library_day", L"seoirin_normal" },
        { L"서이린", L"저는 기억하는 쪽이 익숙하니까요.", L"library_day", L"seoirin_normal" },
        { L"", L"이린은 담담하게 웃었다.", L"library_day", L"seoirin_smile" },
        { L"{PLAYER}", L"이린아.", L"library_day", L"seoirin_normal" },
        { L"서이린", L"붙잡지 않아도 돼요.", L"library_day", L"seoirin_normal" },
        { L"{PLAYER}", L"……", L"library_day", L"seoirin_normal" },
        { L"서이린", L"네가 나를 잊어도 괜찮아요.", L"library_day", L"seoirin_normal" },
        { L"", L"그 말을 끝으로 도서관의 빛이 희미하게 번졌다.", L"library_day", L"seoirin_normal" },
        { L"", L"다음 날, {PLAYER}는 도서관 책상에서 낡은 책갈피 하나를 발견했다.", L"library_day", L"" },
        { L"{PLAYER}", L"이건……", L"library_day", L"" },
        { L"", L"책갈피에는 이름 없는 문장만 적혀 있었다.", L"library_day", L"" },
        { L"책갈피", L"네가 나를 잊어도 괜찮아.", L"library_day", L"" },
        { L"", L"{PLAYER}는 이상하게 가슴이 아팠다.", L"library_day", L"" },
        { L"", L"하지만 끝내 그 문장이 누구의 것인지 기억하지 못했다.", L"library_day", L"" },
        { L"노트", L"봄은 끝났다. 그러나 한 사람의 이름은 책 속에 묻혔다.", L"library_day", L"" },
        { L"엔딩 CG", L"빈 도서관 책상 위에 책갈피만 놓여 있다. {PLAYER}는 그 앞에 앉아 있지만, 이린의 자리는 비어 있다.", L"library_day", L"" }
    };

    endingStories[2][0] =
    {
        { L"", L"검은 노트 위에 이름이 떠오르기 시작했다.", L"school_day", L"" },
        { L"노트", L"한세아.", L"school_day", L"" },
        { L"노트", L"유하린.", L"school_day", L"" },
        { L"노트", L"서이린.", L"school_day", L"" },
        { L"", L"하지만 이름은 하나로 정해지지 못하고 계속 흔들렸다.", L"school_day", L"" },
        { L"{PLAYER}", L"뭐야…… 왜 이름이 안 나와?", L"school_day", L"" },
        { L"노트", L"마음이 충분히 닿지 않았다.", L"school_day", L"" },
        { L"노트", L"봄은 방향을 잃었다.", L"school_day", L"" },
        { L"{PLAYER}", L"방향을 잃었다고?", L"school_day", L"" },
        { L"", L"노트의 마지막 페이지가 스스로 찢어졌다.", L"school_day", L"" },
        { L"???", L"결정을 못 했네?", L"school_day", L"" },
        { L"{PLAYER}", L"누구야?", L"school_day", L"" },
        { L"", L"교실의 불이 꺼졌다.", L"school_day", L"" },
        { L"", L"창밖의 봄이 검은색으로 물들었다.", L"school_day", L"" },
        { L"새누", L"세 명 중 하나도 제대로 못 고르면 어떡해.", L"school_day", L"" },
        { L"{PLAYER}", L"너는……", L"school_day", L"" },
        { L"새누", L"새누. 이 노트의 진짜 주인이라고 해둘까?", L"school_day", L"" },
        { L"{PLAYER}", L"진짜 주인?", L"school_day", L"" },
        { L"새누", L"응. 그리고 이 봄도, 네 세이브 파일도.", L"school_day", L"" },
        { L"{PLAYER}", L"세이브 파일?", L"school_day", L"" },
        { L"새누", L"선택하지 못한 플레이어는 회수 대상이야.", L"school_day", L"" },
        { L"{PLAYER}", L"그런 규칙 들은 적 없는데.", L"school_day", L"" },
        { L"새누", L"히든 루트는 원래 설명 안 해줘.", L"school_day", L"" },
        { L"", L"칠판 위에 붉은 글씨가 떠올랐다.", L"school_day", L"" },
        { L"칠판", L"GAME OVER?\nNO.\nNEW ROUTE.", L"school_day", L"" },
        { L"새누", L"축하해, {PLAYER}.", L"school_day", L"" },
        { L"새누", L"히로인 셋을 전부 놓친 대신……", L"school_day", L"" },
        { L"새누", L"이제 내 루트야.", L"school_day", L"" },
        { L"{PLAYER}", L"잠깐, 그건 좀—", L"school_day", L"" },
        { L"", L"교실 문이 닫히고, 화면이 검게 물들었다.", L"school_day", L"" },
        { L"노트", L"반복되던 봄은 끝나지 않았다.", L"school_day", L"" },
        { L"노트", L"플레이어가 선택하지 못한 봄은, 악마가 가져갔다.", L"school_day", L"" },
        { L"엔딩 CG", L"검은 교실. 새누가 책상 위에 앉아 검은 노트를 들고 웃고 있다. 칠판에는 “NEW ROUTE”라는 붉은 글씨가 떠 있다.", L"school_day", L"" }
    };

    endingStories[2][1] =
    {
        { L"", L"검은 노트 위에 이름이 떠오르기 시작했다.", L"school_day", L"" },
        { L"노트", L"한세아.", L"school_day", L"" },
        { L"노트", L"유하린.", L"school_day", L"" },
        { L"노트", L"서이린.", L"school_day", L"" },
        { L"", L"하지만 이름은 하나로 정해지지 못하고 계속 흔들렸다.", L"school_day", L"" },
        { L"{PLAYER}", L"뭐야…… 왜 이름이 안 나와?", L"school_day", L"" },
        { L"노트", L"마음이 충분히 닿지 않았다.", L"school_day", L"" },
        { L"노트", L"봄은 방향을 잃었다.", L"school_day", L"" },
        { L"{PLAYER}", L"방향을 잃었다고?", L"school_day", L"" },
        { L"", L"노트의 마지막 페이지가 스스로 찢어졌다.", L"school_day", L"" },
        { L"???", L"결정을 못 했네?", L"school_day", L"" },
        { L"{PLAYER}", L"누구야?", L"school_day", L"" },
        { L"", L"교실의 불이 꺼졌다.", L"school_day", L"" },
        { L"", L"창밖의 봄이 검은색으로 물들었다.", L"school_day", L"" },
        { L"새누", L"세 명 중 하나도 제대로 못 고르면 어떡해.", L"school_day", L"" },
        { L"{PLAYER}", L"너는……", L"school_day", L"" },
        { L"새누", L"새누. 이 노트의 진짜 주인이라고 해둘까?", L"school_day", L"" },
        { L"{PLAYER}", L"진짜 주인?", L"school_day", L"" },
        { L"새누", L"응. 그리고 이 봄도, 네 세이브 파일도.", L"school_day", L"" },
        { L"{PLAYER}", L"세이브 파일?", L"school_day", L"" },
        { L"새누", L"선택하지 못한 플레이어는 회수 대상이야.", L"school_day", L"" },
        { L"{PLAYER}", L"그런 규칙 들은 적 없는데.", L"school_day", L"" },
        { L"새누", L"히든 루트는 원래 설명 안 해줘.", L"school_day", L"" },
        { L"", L"칠판 위에 붉은 글씨가 떠올랐다.", L"school_day", L"" },
        { L"칠판", L"GAME OVER?\nNO.\nNEW ROUTE.", L"school_day", L"" },
        { L"새누", L"축하해, {PLAYER}.", L"school_day", L"" },
        { L"새누", L"히로인 셋을 전부 놓친 대신……", L"school_day", L"" },
        { L"새누", L"이제 내 루트야.", L"school_day", L"" },
        { L"{PLAYER}", L"잠깐, 그건 좀—", L"school_day", L"" },
        { L"", L"교실 문이 닫히고, 화면이 검게 물들었다.", L"school_day", L"" },
        { L"노트", L"반복되던 봄은 끝나지 않았다.", L"school_day", L"" },
        { L"노트", L"플레이어가 선택하지 못한 봄은, 악마가 가져갔다.", L"school_day", L"" },
        { L"엔딩 CG", L"검은 교실. 새누가 책상 위에 앉아 검은 노트를 들고 웃고 있다. 칠판에는 “NEW ROUTE”라는 붉은 글씨가 떠 있다.", L"school_day", L"" }
    };

    endingStories[2][2] =
    {
        { L"", L"검은 노트 위에 이름이 떠오르기 시작했다.", L"school_day", L"" },
        { L"노트", L"한세아.", L"school_day", L"" },
        { L"노트", L"유하린.", L"school_day", L"" },
        { L"노트", L"서이린.", L"school_day", L"" },
        { L"", L"하지만 이름은 하나로 정해지지 못하고 계속 흔들렸다.", L"school_day", L"" },
        { L"{PLAYER}", L"뭐야…… 왜 이름이 안 나와?", L"school_day", L"" },
        { L"노트", L"마음이 충분히 닿지 않았다.", L"school_day", L"" },
        { L"노트", L"봄은 방향을 잃었다.", L"school_day", L"" },
        { L"{PLAYER}", L"방향을 잃었다고?", L"school_day", L"" },
        { L"", L"노트의 마지막 페이지가 스스로 찢어졌다.", L"school_day", L"" },
        { L"???", L"결정을 못 했네?", L"school_day", L"" },
        { L"{PLAYER}", L"누구야?", L"school_day", L"" },
        { L"", L"교실의 불이 꺼졌다.", L"school_day", L"" },
        { L"", L"창밖의 봄이 검은색으로 물들었다.", L"school_day", L"" },
        { L"새누", L"세 명 중 하나도 제대로 못 고르면 어떡해.", L"school_day", L"" },
        { L"{PLAYER}", L"너는……", L"school_day", L"" },
        { L"새누", L"새누. 이 노트의 진짜 주인이라고 해둘까?", L"school_day", L"" },
        { L"{PLAYER}", L"진짜 주인?", L"school_day", L"" },
        { L"새누", L"응. 그리고 이 봄도, 네 세이브 파일도.", L"school_day", L"" },
        { L"{PLAYER}", L"세이브 파일?", L"school_day", L"" },
        { L"새누", L"선택하지 못한 플레이어는 회수 대상이야.", L"school_day", L"" },
        { L"{PLAYER}", L"그런 규칙 들은 적 없는데.", L"school_day", L"" },
        { L"새누", L"히든 루트는 원래 설명 안 해줘.", L"school_day", L"" },
        { L"", L"칠판 위에 붉은 글씨가 떠올랐다.", L"school_day", L"" },
        { L"칠판", L"GAME OVER?\nNO.\nNEW ROUTE.", L"school_day", L"" },
        { L"새누", L"축하해, {PLAYER}.", L"school_day", L"" },
        { L"새누", L"히로인 셋을 전부 놓친 대신……", L"school_day", L"" },
        { L"새누", L"이제 내 루트야.", L"school_day", L"" },
        { L"{PLAYER}", L"잠깐, 그건 좀—", L"school_day", L"" },
        { L"", L"교실 문이 닫히고, 화면이 검게 물들었다.", L"school_day", L"" },
        { L"노트", L"반복되던 봄은 끝나지 않았다.", L"school_day", L"" },
        { L"노트", L"플레이어가 선택하지 못한 봄은, 악마가 가져갔다.", L"school_day", L"" },
        { L"엔딩 CG", L"검은 교실. 새누가 책상 위에 앉아 검은 노트를 들고 웃고 있다. 칠판에는 “NEW ROUTE”라는 붉은 글씨가 떠 있다.", L"school_day", L"" }
    };

    endingCredits =
    {
        L"고백은 세이브 로드가 없다",
        L"",
        L"NO SAVE LOVE",
        L"",
        L"기획",
        L"26_WinAPI_Programming_Project",
        L"",
        L"시나리오",
        L"최윤서",
        L"",
        L"프로그래밍",
        L"김새누, 최윤서",
        L"",
        L"캐릭터 이미지",
        L"Created by PixAi, ChatGPT",
        L"",
        L"배경 이미지",
        L"Created by ChatGPT",
        L"",
        L"Title BGM",
        L"Cherry Blossom Route - Created by suno Ai",
        L"",
        L"Ending BGM",
        L"Frozen Truth - Created by suno AI",
        L"테일즈위버 OST - Reminiscence",
        L"MapleStory - Reproduced Abyss A",
        L"",
        L"Story BGM",
        L"MapleStory - YumYum Island : Illiyard Moor",
        L"GODDESS OF VICTORY : NIKKE - Marian",
        L"MapleStory - Lara: Life is Full of Happiness",
        L"Candy Combo Dash - Created by suno Ai",
        L"PRINCESS CONNECT! Re:Dive ORIGINAL SOUNDTRACK - ハッピーエンドのその先で",
        L"MapleStory - Leafre",
        L"MapleStory - Ereve : Raindrop Flower",
        L"Rainy Route - Created by suno Ai",
        L"MapleStory - Sellas : Where Stars Rest",
        L"",
        L"미니게임 - {PLAYER}의 pc방 알바",
        L"제작 : 김새누",
        L"BGM : MapleStory - BadGuys",
        L"Image : Created by ChatGPT",
        L"",
        L"미니게임 - {PLAYER}의 노래연습",
        L"제작 : 김새누",
        L"BGM : QWER - discord",
        L"Image : Created by ChatGPT",
        L"Original Game : OSU, Rhythm Doctor(리듬 닥터)",
        L"",
        L"미니게임 - {PLAYER}의 등교길",
        L"제작 : 최윤서",
        L"BGM : MapleStory - Hotel Arcs: Train Heading Nowhere",
        L"Image : Created by ChatGPT",
        L"",
        L"미니게임 - {PLAYER}의 유혹피하기",
        L"제작 : 최윤서",
        L"BGM : Created by suno Ai",
        L"Image : Created by ChatGPT",
        L"Original Game : 한국밈 피하기",
        L"",
        L"특별자문",
        L"게임공학과 23학번 백지훈",
        L"",
        L"플레이해주셔서 감사합니다",
        L"",
        L"THE END"
    };

}

const std::vector<DialogueLineInfo>& StoryData::GetBranchStory(int roundIndex, int heroineIndex) const
{
    // 회차가 범위를 벗어나면 빈 대사를 반환한다.
    if (roundIndex < 0 || roundIndex >= STORY_ROUND_COUNT)
    {
        return emptyStory;
    }

    // 히로인 번호가 범위를 벗어나면 빈 대사를 반환한다.
    if (heroineIndex < 0 || heroineIndex >= HEROINE_COUNT)
    {
        return emptyStory;
    }

    // 정상 범위라면 해당 회차, 해당 히로인의 스토리를 반환한다.
    return storyScripts[roundIndex][heroineIndex];
}

const std::vector<DialogueLineInfo>& StoryData::GetIntroStory() const
{
    return introStory;
}

const std::vector<DialogueLineInfo>& StoryData::GetFinalChoiceIntroStory(int finalChoiceIndex) const
{
    if (finalChoiceIndex < 0 || finalChoiceIndex >= FINAL_CHOICE_INTRO_COUNT)
    {
        return emptyStory;
    }

    return finalChoiceIntroStories[finalChoiceIndex];
}

const std::vector<DialogueLineInfo>& StoryData::GetEndingStory(int endingType, int heroineIndex) const
{
    if (endingType < 0 || endingType >= ENDING_TYPE_COUNT)
    {
        return emptyStory;
    }

    if (heroineIndex < 0 || heroineIndex >= HEROINE_COUNT)
    {
        return emptyStory;
    }

    return endingStories[endingType][heroineIndex];
}

const std::vector<std::wstring>& StoryData::GetEndingCredits() const
{
    return endingCredits;
}
